Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2020-10, with the labels that each got.

#383 PLANET-5377 Sets translated strings for a JS script
  classes/class-loader.php
Labels: Review

#401 PLANET-5562: Fix htmlentity character on split two columns titles
  assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
Labels: Review

#402 Prevent ever failing a11y from failing all workflows
  .circleci/config.yml
Labels: Review

#404 PLANET-5557 Add Auth creds for all Docker Hub images
  .circleci/config.yml
Labels: Review

#403 PLANET-5373 Remove the "by" string in Articles block author names
  assets/src/blocks/Articles/ArticlePreview.js
Labels: Review

#407 Manually specify master for other repo
  .circleci/config.yml
Labels: Review

#400 PLANET-5468 Columns block: Huge image on the 4th column
  assets/src/styles/blocks/Columns.scss
Labels: Review

#393 Add option for updating the counters in the client
  assets/src/blocks/Counter/CounterFrontend.js
Labels: Review

#380 PLANET-5426 Image block - Removed the blue caption style
  assets/src/ImageBlockExtension.js
  assets/src/styles/blocks/core-overrides/Image.scss
  assets/src/styles/editorOverrides.scss
Labels: DO NOT MERGE, Review

#408 PLANET-4800 Remove Gallery twig template
  templates/blocks/gallery.twig
Labels: Review

#398 PLANET-5463 Disabled "Edit as HTML" block option in articles, counter…
  assets/src/blocks/Articles/ArticlesBlock.js
  assets/src/blocks/Counter/CounterBlock.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Splittwocolumns/SplittwocolumnsBlock.js
Labels: DO NOT MERGE, Review

#412 PLANET-5388 Fix related articles issue on Post
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/Articles/useArticlesFetch.js
  classes/blocks/class-articles.php
  tests/js/articles.frontend.spec.js
Labels: Review

#416 PLANET-5607 No apiFetch on frontend, it breaks wpml and nonces
  assets/src/blocks/Articles/useArticlesFetch.js
  assets/src/blocks/Gallery/GalleryFrontend.js
  assets/src/blocks/Gallery/useGalleryImages.js
  assets/src/blocks/Happypoint/useHappypointImageData.js
  assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
  assets/src/functions/fetchJson.js
  classes/class-loader.php
Labels: Review

#417 Use python2 in zip creation container
  .circleci/config.yml
Labels: Review

#351 PLANET-5221 Check out code for acceptance on fork PRs
  .circleci/config.yml
Labels: Review

#363 PLANET-4811 Submenu WYSIWYG
  assets/src/blocks/Gallery/GalleryBlock.js
  assets/src/blocks/Submenu/MenuLevel.js
  assets/src/blocks/Submenu/Submenu.js
  assets/src/blocks/Submenu/SubmenuBlock.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/Submenu/SubmenuFrontend.js
  assets/src/blocks/Submenu/SubmenuIcon.js
  assets/src/blocks/Submenu/SubmenuItems.js
  assets/src/blocks/Submenu/SubmenuLevel.js
  assets/src/blocks/Submenu/example.js
  assets/src/blocks/Submenu/generateAnchor.js
  assets/src/blocks/Submenu/getHeadingsFromBlocks.js
  assets/src/blocks/Submenu/getHeadingsFromDom.js
  assets/src/blocks/Submenu/getSubmenuStyle.js
  assets/src/blocks/Submenu/makeHierarchical.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/functions/deepClone.js
  assets/src/functions/unescape.js
  assets/src/styles/blocks/Submenu.scss
  assets/src/styles/blocks/SubmenuEditor.scss
  assets/src/styles/components/Preview.scss
  classes/blocks/class-submenu.php
  classes/command/class-shortcode-to-gutenberg.php
  classes/command/converters/class-shortcode-converter-factory.php
  classes/command/converters/class-submenu-converter.php
  public/js/submenu.js
  templates/blocks/submenu.twig
  tests/unit/test-shortcode-converter.php
Labels: Review, UAT Passed

#421 PLANET-5501 Update EN form button styles
  assets/src/styles/blocks/ENForm/components/_enform.scss
Labels: Review
