Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2021-12, with the labels that each got.

#742 Enable GravityForms Gutenberg block
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] venus

#729 Fine tune Carousel Header slide re-ordering design and UX
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/blocks/CarouselHeader/SidebarSlide.js
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
  assets/src/styles/blocks/CarouselHeader/SidebarSlidesEditor.scss
Labels: Review, UAT Passed, [Test Env] atlas

#743 PLANET-6500 Gallery: Adjust image widths for XXL container
  assets/src/styles/blocks/Gallery/styles/GalleryThreeColumns.scss
Labels: Review, [Test Env] uranus

#744 Allow multiple boxouts, remove id attribute
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
  templates/blocks/take-action-boxout.twig
Labels: Review, [Test Env] iocaste

#733 Workaround to prevent local images CarouselHeader
  assets/src/blocks/CarouselHeader/EditableBackground.js
  classes/class-loader.php
Labels: Review, [Test Env] neptune

#747 Fix small typo in Settings panel title
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Counter/CounterEditor.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Gallery/GalleryEditor.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  assets/src/blocks/Splittwocolumns/SplittwocolumnsSettings.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
  tests/js/articles.editor.spec.js
  tests/js/articles.frontend.spec.js
  tests/js/counter.spec.js
  tests/js/spreadsheet.spec.js
  tests/js/submenu.spec.js
Labels: Review, [Test Env] nix

#726 PLANET-6475 Add mobile sticky behavior to Take Action Boxout
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
  assets/src/styles/blocks/TakeActionBoxout/edit.scss
  assets/src/styles/blocks/TakeActionBoxout/style.scss
  classes/blocks/class-takeactionboxout.php
  public/images/close-boxout.svg
  templates/blocks/take-action-boxout.twig
Labels: UAT Passed, [Test Env] pluto

#748 PLANET-6482 Fix Accordion block button width in the editor
  assets/src/styles/blocks/Accordion/AccordionEditorStyle.scss
Labels: Review, [Test Env] deimos

#734 PLANET-5609 Covers block carousel layout
  assets/src/blocks/Covers/CampaignCovers.js
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Covers/Covers.js
  assets/src/blocks/Covers/CoversCarouselControls.js
  assets/src/blocks/Covers/CoversConstants.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/CoversFrontend.js
  assets/src/blocks/Covers/CoversGridLoadMoreButton.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Covers/useCovers.js
  assets/src/styles/blocks/Covers/CoversStyle.scss
  assets/src/styles/blocks/Covers/layouts/ContentCovers.scss
  assets/src/styles/blocks/Covers/layouts/CoversCarouselLayout.scss
  assets/src/styles/blocks/Covers/layouts/CoversGridLayout.scss
  assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
  assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
  assets/src/styles/blocks/Covers/styles/ContentCovers.scss
  assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
  classes/blocks/class-covers.php
  tests/acceptance/CoversContentCept.php
Labels: Review, UAT Passed, [Test Env] jupiter

#750 Bump theme editor
  package-lock.json
  package.json
Labels: Review, [Test Env] neptune

#740 PLANET-6489: Reduce data included in Covers block
  classes/blocks/class-covers.php
Labels: [Test Env] sinope

#751 PLANET-5609 Fix existing Covers blocks in the backend
  assets/src/blocks/Covers/deprecated/coversV1.js
Labels: Review

#752 PLANET-6106 Use block examples for Covers styles
  assets/src/blocks/Covers/CampaignCovers.js
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/CoversImagePlaceholder.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Covers/example.js
  assets/src/styles/blocks/Covers/CoversEditorStyle.scss
  classes/blocks/class-covers.php
  webpack.config.js
Labels: Review, [Test Env] nix

#753 Allow lite-youtube element in Media test
  tests/acceptance/MediaCept.php
Labels: [Test Env] rhea
