Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2021-07, with the labels that each got.

#546 PLANET-6040 Fix articles block, Block validation error
  assets/src/blocks/Articles/ArticlesBlock.js
Labels: Review

#625 PLANET-5662 Split webpack into multiple configs
  package-lock.json
  package.json
  webpack.config.js
Labels: Review

#594 A11y: Address accessibility of spreadsheet block
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
  assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
Labels: Review

#598 PLANET-5247 (Just for running protected tests against fork code) A11y: Address accessibility of spreadsheet block
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
  assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
Labels: DO NOT MERGE

#624 PLANET-6124: Fix the "open in a new tab" functionality through from settings
  assets/src/blocks/Columns/Columns.js
  assets/src/blocks/Columns/ColumnsEditor.js
Labels: Review

#629 Move PR check in a script
  .circleci/config.yml
Labels: Review, [Test Env] phoebe

#453 PLANET-4814: Convert EN Form block to WYSIWYG
  assets/src/blocks/ENForm/CountrySelector.js
  assets/src/blocks/ENForm/ENFormBlock.js
  assets/src/blocks/ENForm/ENFormEditor.js
  assets/src/blocks/ENForm/ENFormEditorScript.js
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  assets/src/blocks/ENForm/ENFormScript.js
  assets/src/blocks/ENForm/ENFormSettings.js
  assets/src/blocks/ENForm/FormGenerator.js
  assets/src/blocks/ENForm/PositionSelector.js
  assets/src/blocks/ENForm/ShareButtons.js
  assets/src/blocks/ENForm/SvgIcon.js
  assets/src/blocks/ENForm/inputName.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks/ENForm/ENFormEditorStyle.scss
  assets/src/styles/blocks/ENForm/ENFormStyle.scss
  assets/src/styles/blocks/ENForm/components/_enform-side-style.scss
  assets/src/styles/blocks/ENForm/components/_enform.scss
  assets/src/styles/blocks/OldENForm/ENFormEditor.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-base-block.php
  classes/blocks/class-enform.php
  classes/blocks/class-oldenform.php
  classes/class-loader.php
  classes/controller/menu/class-enform-post-controller.php
  classes/rest/class-rest-api.php
  planet4-gutenberg-blocks.php
  webpack.config.js
Labels: Review, [Test Env] venus

#589 PLANET-6136 Add select for new themes
  assets/src/components/Sidebar/CampaignSidebar.js
  assets/src/components/Sidebar/NewThemeSettings.js
  classes/class-loader.php
  package-lock.json
  package.json
  templates/blocks/css_variables.twig
Labels: Review, [Test Env] pluto
