Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2021-08, with the labels that each got.

#635 PLANET-6083: Pass utm_medium param to share buttons Twig template
  templates/blocks/enform/tease-thankyou.twig
Labels: Review

#628 Add CSS variables to Articles, Columns and Covers
  assets/src/styles/blocks/Articles.scss
  assets/src/styles/blocks/Columns.scss
  assets/src/styles/blocks/Covers/ContentCovers.scss
Labels: Review, [Test Env] saturn

#638 Add missing quotes
  .circleci/config.yml
Labels: Review, [Test Env] oberon

#640 Remove large-and-up media query of Columns tasks
  assets/src/styles/blocks/Columns.scss
Labels: Review, [Test Env] uranus

#623 PLANET-6198 Convert SocialMedia block to WYSIWYG
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/Media/MediaEmbedPreview.js
  assets/src/blocks/Media/MediaFrontend.js
  assets/src/blocks/SocialMedia/SocialMediaBlock.js
  assets/src/blocks/SocialMedia/SocialMediaConstants.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  assets/src/blocks/SocialMedia/SocialMediaEmbed.js
  assets/src/blocks/SocialMedia/SocialMediaFrontend.js
  assets/src/blocks/SocialMedia/deprecated/socialMediaV1.js
  assets/src/blocks/Socialmedia/Socialmedia.js
  assets/src/blocks/Socialmedia/SocialmediaBlock.js
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/SocialMedia/SocialMediaStyle.scss
  classes/blocks/class-socialmedia.php
  classes/command/converters/class-shortcode-converter-factory.php
  classes/command/converters/class-socialmedia-converter.php
  classes/rest/class-rest-api.php
  tests/unit/test-shortcode-converter.php
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] sinope

#639 PLANET-5608 Duplicate Covers block CSS files
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Covers/CoversEditorStyle.scss
  assets/src/styles/blocks/Covers/CoversStyle.scss
  assets/src/styles/blocks/Covers/boxout/TakeActionBoxoutBottom.scss
  assets/src/styles/blocks/Covers/boxout/TakeActionBoxoutScroll.scss
  assets/src/styles/blocks/Covers/layouts/CampaignCovers.scss
  assets/src/styles/blocks/Covers/layouts/ContentCovers.scss
  assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
  assets/src/styles/blocks/OldCovers/CampaignCovers.scss
  assets/src/styles/blocks/OldCovers/ContentCovers.scss
  assets/src/styles/blocks/OldCovers/TakeActionBoxoutBottom.scss
  assets/src/styles/blocks/OldCovers/TakeActionBoxoutScroll.scss
  assets/src/styles/blocks/OldCovers/TakeActionCovers.scss
  webpack.config.js
Labels: Review

#643 Some more blocks variables (ENForm and Counter), bump theme editor
  assets/src/styles/blocks/Counter.scss
  assets/src/styles/blocks/OldENForm/components/_enform.scss
  package-lock.json
  package.json
Labels: Review, [Test Env] pluto

#646 PLANET-5608 Implement new Take Action cover designs
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
  assets/src/styles/blocks/OldCovers/TakeActionCovers.scss
Labels: Review, UAT Passed, [Test Env] iocaste

#648 Get hydration to work
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
  assets/src/blocks/CarouselHeader/EditableBackground.js
  assets/src/blocks/CarouselHeader/EditorControls.js
  assets/src/blocks/CarouselHeader/SlideBackground.js
  assets/src/blocks/CarouselHeader/deprecated/carouselHeaderV1.js
  assets/src/blocks/CarouselHeader/migrate.js
  assets/src/blocks/CarouselHeader/useCarouselHeaderImages.js
  assets/src/blocks/CarouselHeader/useSlides.js
  assets/src/functions/hydrateBlock.js
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
  classes/blocks/class-carouselheader.php
  package-lock.json
  package.json
Labels: Review, [Test Env] leda

#650 Switch Carousel Header to WYSIWYG version
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
  assets/src/blocks/OldCarouselheader/CarouselHeader.js
  assets/src/blocks/OldCarouselheader/CarouselHeaderBlock.js
  assets/src/blocks/OldCarouselheader/CarouselHeaderFront.js
  assets/src/blocks/OldCarouselheader/CarouselHeaderImage.js
  assets/src/blocks/OldCarouselheader/CarouselHeaderSlide.js
  assets/src/blocks/OldCarouselheader/FullWidthCarouselHeader.js
  assets/src/blocks/OldCarouselheader/ImagePlaceholder.js
  assets/src/carouselHeaderFrontIndex.js
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/styles/blocks/OldCarouselHeader.scss
  assets/src/styles/blocks/OldCarouselHeaderEditor.scss
  assets/src/styles/blocks/OldCarouselHeaderEditorOverrides.scss
  assets/src/styles/blocks/OldCarouselHeader_full_width_classic.scss
  assets/src/styles/campaigns/block-overrides/_campaign_carousel_header.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-base-block.php
  classes/blocks/class-carouselheader.php
  classes/blocks/class-oldcarouselheader.php
  classes/class-loader.php
  planet4-gutenberg-blocks.php
  tests/acceptance/CarouselHeaderClassicCept.php
  webpack.config.js
Labels: Review, [Test Env] phoebe
