Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2021-04, with the labels that each got.

#545 PLANET-5983: Simple way to save themes, some small improvements
  assets/src/styles/components/VarPicker.scss
  assets/src/theme/VarPicker.js
  assets/src/theme/VariableControl.js
  assets/src/theme/dragElement.js
  assets/src/theme/getMatchingVars.js
  assets/src/theme/groupVars.js
  assets/src/theme/initializeThemeEditor.js
  assets/src/theme/typedControl.js
  assets/src/theme/useServerThemes.js
  assets/src/theme/useThemeEditor.js
  classes/class-loader.php
  classes/rest/class-rest-api.php
Labels: Review

#547 PLANET-6045 Add relevant Acceptance tests
  phpcs.xml
  tests/acceptance/CarouselHeaderClassicCept.php
  tests/acceptance/ColumnsIconsCept.php
  tests/acceptance/ColumnsImagesCept.php
  tests/acceptance/ColumnsNoImageCept.php
  tests/acceptance/ColumnsTasksCept.php
  tests/acceptance/CoversCampaignCept.php
  tests/acceptance/CoversContentCept.php
  tests/acceptance/CoversTakeActionCept.php
  tests/acceptance/ENFormCest.php
  tests/acceptance/MediaCept.php
  tests/acceptance/SplitTwoColumnsCept.php
  tests/acceptance/TakeActionBoxoutCept.php
Labels: Review

#548 PLANET-5983: Properly extract vars from multiple files
  package-lock.json
  package.json
  webpack.config.js
Labels: Review

#550 PLANET-5983 Theme editor quick UX wins
  assets/src/theme/VarPicker.js
  assets/src/theme/dragElement.js
  assets/src/theme/groupVars.js
  assets/src/theme/typedControl.js
  assets/src/theme/useLocalStorage.js
  assets/src/theme/useServerThemes.js
Labels: Review

#557 PLANET-5983 Follow variable name change
  assets/src/styles/campaigns/themes/_theme_antarctic.scss
  assets/src/styles/campaigns/themes/_theme_arctic.scss
  assets/src/styles/campaigns/themes/_theme_climate.scss
  assets/src/styles/campaigns/themes/_theme_forest.scss
  assets/src/styles/campaigns/themes/_theme_oceans.scss
  assets/src/styles/campaigns/themes/_theme_oil.scss
  assets/src/styles/campaigns/themes/_theme_plastic.scss
Labels: Review

#561 PLANET-6087 Move SubPages, Spreadsheet and Accordion to stable category
  assets/src/blocks/Accordion/AccordionEditorScript.js
  assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
  assets/src/blocks/SubPages/SubPagesBlock.js
Labels: Review

#562 PLANET-6072 Fix Sentry issue: PLANET4-RS
  classes/blocks/class-spreadsheet.php
Labels: Review

#552 PLANET-5983 Make CSS variables file work with WPML
  assets/src/theme/initializeThemeEditor.js
Labels: Review

#565 Improve ordering and exclude bootstrap variables
  assets/src/theme/getMatchingVars.js
  assets/src/theme/groupVars.js
Labels: Review

#556 PLANET-6080 Move fonts out of CSS file
  assets/src/styles/campaigns/base/_fonts.scss
  assets/src/styles/campaigns/base/_google_fonts.scss
  assets/src/styles/editorStyle.scss
Labels: Review

#564 PLANET-6086 Code splitting Covers block
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/CoversScript.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks/Covers/CoversEditorStyle.scss
  assets/src/styles/blocks/Covers/CoversStyle.scss
  classes/blocks/class-base-block.php
  classes/blocks/class-covers.php
  webpack.config.js
Labels: Review

#570 Add a job for posting a PR comment when test instance is ready
  .circleci/config.yml
Labels: Review

#483 PLANET-4809: WYSIWYG Carousel Header
  assets/src/blocks/CarouselHeader/Arrows.js
  assets/src/blocks/CarouselHeader/ArrowsAndIndicators.js
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditorScript.js
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
  assets/src/blocks/CarouselHeader/CarouselHeaderStaticContent.js
  assets/src/blocks/CarouselHeader/EditableBackground.js
  assets/src/blocks/CarouselHeader/EditorControls.js
  assets/src/blocks/CarouselHeader/ImagePlaceholder.js
  assets/src/blocks/CarouselHeader/Indicators.js
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/blocks/CarouselHeader/SidebarSlide.js
  assets/src/blocks/CarouselHeader/Slide.js
  assets/src/blocks/CarouselHeader/SlideBackground.js
  assets/src/blocks/CarouselHeader/SlidesContainer.js
  assets/src/blocks/CarouselHeader/StaticCaption.js
  assets/src/blocks/CarouselHeader/deprecated/carouselHeaderV1.js
  assets/src/blocks/CarouselHeader/migrate.js
  assets/src/blocks/CarouselHeader/useCarouselHeaderImages.js
  assets/src/blocks/CarouselHeader/useSlides.js
  assets/src/blocks/Carouselheader/CarouselHeader.js
  assets/src/blocks/Carouselheader/CarouselHeaderBlock.js
  assets/src/blocks/Carouselheader/CarouselHeaderFront.js
  assets/src/blocks/Carouselheader/CarouselHeaderImage.js
  assets/src/blocks/Carouselheader/CarouselHeaderSlide.js
  assets/src/blocks/Carouselheader/FullWidthCarouselHeader.js
  assets/src/blocks/Carouselheader/ImagePlaceholder.js
  assets/src/components/URLValidationMessage/URLValidationMessage.js
  assets/src/functions/hydrateBlock.js
  assets/src/styles/blocks/CarouselHeader.scss
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/styles/blocks/CarouselHeaderEditor.scss
  assets/src/styles/blocks/CarouselHeaderEditorOverrides.scss
  assets/src/styles/campaigns/block-overrides/_campaign_carousel_header.scss
  classes/blocks/class-base-block.php
  classes/blocks/class-carouselheader.php
  classes/command/converters/class-carouselheader-converter.php
  classes/command/converters/class-shortcode-converter-factory.php
  planet4-gutenberg-blocks.php
  tests/unit/test-shortcode-converter.php
  webpack.config.js
Labels: Review, UAT needed

#539 PLANET-4802 Columns block WYSIWYG
  assets/src/blocks/Columns/ColumnConstants.js
  assets/src/blocks/Columns/Columns.js
  assets/src/blocks/Columns/ColumnsBlock.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Columns/ColumnsFrontend.js
  assets/src/blocks/Columns/ColumnsImagePlaceholder.js
  assets/src/blocks/Columns/ColumnsTasks.js
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/blocks/Columns/example.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks/Columns.scss
  assets/src/styles/blocks/ColumnsEditor.scss
  classes/blocks/class-columns.php
  classes/command/class-shortcode-to-gutenberg.php
  classes/command/converters/class-columns-converter.php
  classes/command/converters/class-shortcode-converter-factory.php
  public/js/columns.js
  templates/blocks/columns.twig
  templates/blocks/columns_tasks.twig
  tests/acceptance/ColumnsImagesCept.php
  tests/unit/test-shortcode-converter.php
Labels: Review, UAT Passed

#523 PLANET-5983: Add variables to blocks CSS, part I
  assets/src/styles/blocks/Articles.scss
  assets/src/styles/blocks/Columns.scss
  assets/src/styles/blocks/Covers/TakeActionCovers.scss
  assets/src/styles/blocks/ENForm/components/_enform.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: Review

#573 PLANET-4809 Enqueue hammer only if block is present
  classes/blocks/class-carouselheader.php
Labels: Review
