Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2021-03, with the labels that each got.

#498 PLANET-5843 Replace some colors to align with the design system
  admin/css/admin_en.css
  assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
  assets/src/styles/blocks/Columns.scss
  assets/src/styles/blocks/Covers/CampaignCovers.scss
  assets/src/styles/blocks/Covers/TakeActionBoxoutBottom.scss
  assets/src/styles/blocks/Covers/TakeActionBoxoutScroll.scss
  assets/src/styles/blocks/Covers/TakeActionCovers.scss
  assets/src/styles/blocks/ENForm/components/_enform-side-style.scss
  assets/src/styles/blocks/ENForm/components/_enform.scss
  assets/src/styles/blocks/SplitTwoColumns.scss
  assets/src/styles/blocks/Submenu.scss
  assets/src/styles/campaigns/components/_campaign_covers.scss
  assets/src/styles/campaigns/themes/_theme_antarctic.scss
  assets/src/styles/editorOverrides.scss
  classes/class-loader.php
Labels: HOLD, UAT Passed

#505 PLANET-5906: Migrate to Bootstrap 5
  assets/src/blocks/Gallery/GalleryCarousel.js
  templates/blocks/carousel_header_full-width-classic.twig
Labels: Review

#522 Fix base branch and name
  .circleci/config.yml
Labels: Review

#524 PLANET-5990 Enable Social Media block on Posts
  planet4-gutenberg-blocks.php
Labels: Review

#525 PLANET-5985: Too much padding bottom for new YouTube embed
  assets/src/styles/blocks/Media.scss
Labels: Review

#461 PLANET-4590: Image block: Photo credit/copyright is not visible in the editor
  assets/src/BlockFilters.js
  assets/src/components/Image/ImageBlockEdit.js
Labels: Review

#528 Prevent unneeded prefixes, we autoprefix
  .stylelintrc
  assets/src/styles/blocks/Accordion.scss
  assets/src/styles/blocks/Covers/TakeActionBoxoutBottom.scss
  assets/src/styles/blocks/Covers/TakeActionBoxoutScroll.scss
  assets/src/styles/blocks/Gallery_carousel.scss
  assets/src/styles/blocks/SplitTwoColumns.scss
  assets/src/styles/blocks/Submenu.scss
  assets/src/styles/campaigns/base/_mixins.scss
  assets/src/styles/campaigns/themes/_theme_climate.scss
  assets/src/styles/campaigns/themes/_theme_oil.scss
  assets/src/styles/components/VarPicker.scss
  assets/src/styles/vendors/photoswipe/main.scss
  assets/src/styles/vendors/photoswipe/p4-skin.scss
Labels: Review

#479 WordPress 5.6 preparation
  .circleci/config.yml
  admin/js/editor.js
  assets/src/BlockFilters.js
  assets/src/ImageBlockExtension.js
  assets/src/RichTextEnhancements.js
  assets/src/components/p4_button/color-edit.js
  assets/src/components/p4_button/color-props.js
  assets/src/components/p4_button/edit.js
  assets/src/components/p4_table/edit.js
  assets/src/editorIndex.js
  assets/src/styles/components/Preview.scss
  assets/src/styles/editorOverrides.scss
  bin/install-wp-tests.sh
  classes/controller/menu/class-blocks-usage-controller.php
  planet4-gutenberg-blocks.php
Labels: DO NOT MERGE, WIP

#519 PLANET-5980 Fix inconsistencies between editor and frontend
  assets/src/styles/blocks/File.scss
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review

#535 PLANET-5981 Fix CarouselHeader indicators
  assets/src/blocks/Carouselheader/FullWidthCarouselHeader.js
  assets/src/styles/blocks/CarouselHeader_full_width_classic.scss
Labels: Review

#537 PLANET-6015: Handle post locking in subscriber
  assets/src/BlockEditorValidation.js
  assets/src/blocks/Carouselheader/CarouselHeaderBlock.js
Labels: Review

#536 PLANET-5986 Disable Take Action Boxout from Pages
  planet4-gutenberg-blocks.php
Labels: Review

#538 PLANET-6027 Don't load icons twice
  assets/src/styles/campaigns.scss
Labels: Review

#540 PLANET-6030 Unset 100vw width of Carousel Header in editor
  assets/src/styles/blocks/CarouselHeaderEditorOverrides.scss
Labels: Review

#542 Upgrade github-archive-installer to support composer 2
  composer.json
  composer.lock
Labels: Review

#531 PLANET-6004 Fix external and pdf link icons in campaigns
  assets/src/styles/campaigns/themes/_theme_antarctic.scss
  assets/src/styles/campaigns/themes/_theme_arctic.scss
  assets/src/styles/campaigns/themes/_theme_climate.scss
  assets/src/styles/campaigns/themes/_theme_forest.scss
  assets/src/styles/campaigns/themes/_theme_oceans.scss
  assets/src/styles/campaigns/themes/_theme_oil.scss
Labels: Review

#508 PLANET-4535: Perf: Split blocks JS into chunks where possible
  assets/src/blocks/Accordion/AccordionEditorScript.js
  assets/src/blocks/Accordion/AccordionScript.js
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Accordion/AccordionEditorStyle.scss
  assets/src/styles/blocks/Accordion/AccordionStyle.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-accordion.php
  classes/blocks/class-articles.php
  classes/blocks/class-base-block.php
  classes/blocks/class-carouselheader.php
  classes/blocks/class-columns.php
  classes/blocks/class-cookies.php
  classes/blocks/class-counter.php
  classes/blocks/class-covers.php
  classes/blocks/class-enform.php
  classes/blocks/class-gallery.php
  classes/blocks/class-happypoint.php
  classes/blocks/class-media.php
  classes/blocks/class-socialmedia.php
  classes/blocks/class-socialmediacards.php
  classes/blocks/class-splittwocolumns.php
  classes/blocks/class-spreadsheet.php
  classes/blocks/class-submenu.php
  classes/blocks/class-subpages.php
  classes/blocks/class-takeactionboxout.php
  classes/blocks/class-timeline.php
  classes/class-loader.php
  classes/command/converters/class-covers-converter.php
  classes/rest/class-rest-api.php
  templates/blocks/carousel-header.twig
  templates/blocks/media-video.twig
  templates/blocks/social-media.twig
  templates/blocks/take-action-boxout.twig
  webpack.config.js
Labels: Review

#534 [No issue]: Check for a truish value in err before logging it
  webpack.config.js
Labels: Review

#520 PLANET-5984 Checkbox/radio validation issues in EN forms
  assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
  assets/src/styles/blocks/ENForm/components/_enform.scss
  public/js/enform_submit.js
  templates/blocks/enform/enform_post.twig
Labels: Review
