Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2021-11, with the labels that each got.

#706 PLANET-6456 Replace Accordion arrow icon
  assets/src/styles/blocks/Accordion/AccordionStyle.scss
Labels: Review, [Test Env] phobos

#708 PLANET-6455 Ensure boxout always scrolls
  public/js/post_action.js
Labels: [Test Env] saturn

#709 PLANET-6460 Use click to ensure keyboard accessibility on Covers load more
  public/js/load_more.js
Labels: Review, [Test Env] umbriel

#710 Fix display and focus of Articles image link
  assets/src/blocks/Articles/ArticlePreview.js
  assets/src/styles/blocks/Articles.scss
Labels: Review, [Test Env] pandora

#712 PLANET-6464 Remove highly specific text color rule on boxout that caused regression in GPNL child theme
  assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
  assets/src/styles/blocks/OldCovers/TakeActionCovers.scss
Labels: [Test Env] sinope

#713 Add Carousel indicator color variable in repo where it's used
  assets/src/styles/blocks/Gallery_carousel.scss
Labels: Review, [Test Env] venus

#711 PLANET-6006 Align Gallery carousel with design system
  assets/src/blocks/Gallery/GalleryBlock.js
  assets/src/blocks/Gallery/GalleryCarousel.js
  assets/src/blocks/Gallery/GalleryEditorScript.js
  assets/src/blocks/Gallery/GalleryScript.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Gallery/GalleryEditorStyle.scss
  assets/src/styles/blocks/Gallery/GalleryStyle.scss
  assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
  assets/src/styles/blocks/Gallery/styles/GalleryGrid.scss
  assets/src/styles/blocks/Gallery/styles/GalleryThreeColumns.scss
  assets/src/styles/blocks/Gallery_carousel.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-gallery.php
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] atlas

#714 PLANET-6006 Fix Gallery carousel backend
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/blocks/Counter/CounterEditor.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  assets/src/blocks/Gallery/GalleryCarousel.js
  assets/src/blocks/Gallery/GalleryEditor.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
Labels: Review

#719 Make sure unit tests run on the right WP version
  .circleci/config.yml
  bin/install-wp-tests.sh
  composer.json
  composer.lock
Labels: Review

#715 PLANET-6379 New Posts & Covers & Take Action Boxout block designs
  admin/js/editor.js
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Covers/imageSizes.js
  assets/src/blocks/OldCovers/Covers.js
  assets/src/blocks/OldCovers/CoversBlock.js
  assets/src/blocks/OldCovers/CoversIcon.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Covers/CoversStyle.scss
  assets/src/styles/blocks/Covers/boxout/TakeActionBoxoutBottom.scss
  assets/src/styles/blocks/Covers/boxout/TakeActionBoxoutScroll.scss
  assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
  assets/src/styles/blocks/OldCovers/CampaignCovers.scss
  assets/src/styles/blocks/OldCovers/ContentCovers.scss
  assets/src/styles/blocks/OldCovers/TakeActionBoxoutEditor.scss
  assets/src/styles/blocks/OldCovers/TakeActionBoxoutScroll.scss
  assets/src/styles/blocks/OldCovers/TakeActionCovers.scss
  assets/src/styles/blocks/TakeActionBoxout/edit.scss
  assets/src/styles/blocks/TakeActionBoxout/style.scss
  assets/src/styles/blocks/TakeActionBoxoutEditor.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-base-block.php
  classes/blocks/class-covers.php
  classes/blocks/class-oldcovers.php
  classes/blocks/class-takeactionboxout.php
  classes/class-loader.php
  planet4-gutenberg-blocks.php
  public/js/post_action.js
  templates/blocks/old_covers.twig
  templates/blocks/take-action-boxout.twig
  tests/acceptance/CoversTakeActionCept.php
  tests/acceptance/TakeActionBoxoutCept.php
Labels: [Test Env] sinope

#722 Keep tests folder on zip creation
  .circleci/config.yml
Labels: Review, [Test Env] atlas

#730 Decouple image hover controls from Columns block
  assets/src/blocks/CarouselHeader/ImagePlaceholder.js
  assets/src/blocks/Columns/ColumnsImagePlaceholder.js
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/components/ImageHoverControls/index.js
  assets/src/components/ImagePlaceholderIcon.js
Labels: [Test Env] pandora

#731 Carousel Header: Remove redundant transform on previous icon
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
Labels: [Test Env] uranus

#728 Update to default if dependency has no options
  assets/src/components/fromThemeOptions/fromThemeOptions.js
Labels: [Test Env] sinope

#732 PLANET-6471 Use same image controls as Columns block
  assets/src/blocks/TakeActionBoxout/ImagePlaceholder.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/components/ImageHoverControls/index.js
  assets/src/styles/blocks/ColumnsEditor.scss
  assets/src/styles/blocks/TakeActionBoxout/edit.scss
Labels: Review, [Test Env] venus

#735 Remove old Covers files and code
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/styles/blocks/Covers/layouts/CampaignCovers.scss
  assets/src/styles/blocks/Covers/layouts/ContentCovers.scss
  assets/src/styles/blocks/Covers/layouts/TakeActionCovers.scss
  public/images/campaign_covers.png
  public/images/content_covers.png
  public/images/take_action_covers.png
  public/js/load_more.js
  templates/blocks/campaign_covers.twig
  templates/blocks/content_covers.twig
  templates/blocks/covers.twig
Labels: Review

#737 Remove blocks container classes
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Columns/ColumnsFrontend.js
  assets/src/blocks/Counter/CounterFrontend.js
  assets/src/blocks/Covers/CampaignCovers.js
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Gallery/GalleryEditor.js
  assets/src/blocks/Gallery/GalleryFrontend.js
  assets/src/blocks/Media/MediaFrontend.js
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
  assets/src/styles/blocks/ENForm/components/_enform.scss
  assets/src/styles/blocks/Media.scss
  assets/src/styles/blocks/OldENForm/components/_enform-full-width.scss
  assets/src/styles/blocks/OldENForm/components/_enform.scss
  tests/acceptance/ColumnsImagesCept.php
Labels: [Test Env] uranus
