Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2021-09, with the labels that each got.

#647 PLANET-6362 Add new version of themes
  assets/src/components/Sidebar/LegacyThemeSettings.js
  assets/src/components/Sidebar/NewThemeSettings.js
Labels: [Test Env] pluto

#654 Remove characterLimit prop that only results in console warnings
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/blocks/Counter/CounterEditor.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  assets/src/blocks/Gallery/GalleryEditor.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
  assets/src/blocks/Submenu/SubmenuEditor.js
Labels: Review, [Test Env] tavros

#652 Deprecate frontendRendered function
  assets/src/blocks/frontendRendered.js
Labels: Review, [Test Env] rhea

#655 PLANET-6137 Allow re-ordering slides
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
Labels: Review, [Test Env] titan

#653 PLANET-6253 Add analytical cookies option in cookies block
  assets/src/blocks/Cookies/CookiesBlock.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  classes/blocks/class-cookies.php
  classes/class-loader.php
Labels: Review, UAT Passed, [Test Env] oberon

#657 Remove cookie that gets set on render
  assets/src/blocks/Cookies/CookiesFrontend.js
Labels: [Test Env] sinope

#656 Enable Hubspot form block
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] uranus

#660 Allow theming counter block spacing and display
  assets/src/styles/blocks/Counter.scss
  assets/src/styles/blocks/ENForm/components/_enform-side-style.scss
  assets/src/styles/blocks/OldENForm/components/_enform-side-style.scss
Labels: Review, [Test Env] pluto

#664 Remove code of legacy themes
  assets/src/components/Sidebar/LegacyThemeSettings.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/ENForm/ENFormStyle.scss
  assets/src/styles/campaigns.scss
  assets/src/styles/campaigns/base/_fonts.scss
  assets/src/styles/campaigns/base/_google_fonts.scss
  assets/src/styles/campaigns/base/_mixins.scss
  assets/src/styles/campaigns/base/_variables.scss
  assets/src/styles/campaigns/block-overrides/_campaign_articles.scss
  assets/src/styles/campaigns/block-overrides/_campaign_buttons.scss
  assets/src/styles/campaigns/block-overrides/_campaign_carousel.scss
  assets/src/styles/campaigns/block-overrides/_campaign_carousel_header.scss
  assets/src/styles/campaigns/block-overrides/_campaign_columns.scss
  assets/src/styles/campaigns/block-overrides/_campaign_content_covers.scss
  assets/src/styles/campaigns/block-overrides/_campaign_counter.scss
  assets/src/styles/campaigns/block-overrides/_campaign_happy_point.scss
  assets/src/styles/campaigns/block-overrides/_campaign_social_media_cards.scss
  assets/src/styles/campaigns/block-overrides/_campaign_split_two_columns.scss
  assets/src/styles/campaigns/block-overrides/_campaign_submenu.scss
  assets/src/styles/campaigns/components/_campaign_covers.scss
  assets/src/styles/campaigns/components/_campaign_video.scss
  assets/src/styles/campaigns/themes/_theme_antarctic.scss
  assets/src/styles/campaigns/themes/_theme_arctic.scss
  assets/src/styles/campaigns/themes/_theme_climate.scss
  assets/src/styles/campaigns/themes/_theme_forest.scss
  assets/src/styles/campaigns/themes/_theme_oceans.scss
  assets/src/styles/campaigns/themes/_theme_oil.scss
  assets/src/styles/campaigns/themes/_theme_plastic.scss
  assets/src/styles/editorStyle.scss
  assets/src/styles/theme_antarctic.scss
  assets/src/styles/theme_arctic.scss
  assets/src/styles/theme_climate.scss
  assets/src/styles/theme_forest.scss
  assets/src/styles/theme_oceans.scss
  assets/src/styles/theme_oil.scss
  assets/src/styles/theme_plastic.scss
  classes/class-loader.php
  webpack.config.js
Labels: Review, [Test Env] nix

#665 Set theme variables on page load
  assets/src/components/Sidebar/CampaignSidebar.js
  assets/src/components/Sidebar/NewThemeSettings.js
  assets/src/styles/editorFonts.scss
  assets/src/styles/editorStyle.scss
Labels: [Test Env] phoebe

#666 Fix cli command in test for wp-browser update
  tests/acceptance/ENFormCest.php
Labels: [Test Env] saturn

#668 Use files from renamed location
  assets/src/components/Sidebar/CampaignSidebar.js
Labels: Review, [Test Env] sinope

#669 Extract complex theme switching logic to separate functions (preparation before converting to hooks)
  assets/src/components/Sidebar/CampaignSidebar.js
  assets/src/components/fromThemeOptions/fromThemeOptions.js
Labels: Review, [Test Env] tavros

#670 Fix empty CarouselHeader page crash
  assets/src/blocks/CarouselHeader/deprecated/carouselHeaderV1.js
Labels: Review

#672 Add RTL css to Submenu block
  assets/src/styles/blocks/Submenu.scss
  assets/src/styles/blocks/SubmenuEditor.scss
Labels: Review, [Test Env] uranus

#671 Use hooks instead of HOCs for theme sidebar
  assets/src/components/PostMeta/withPostMeta.js
  assets/src/components/Sidebar/CampaignSidebar.js
  assets/src/components/Sidebar/LegacyThemeSettings.js
  assets/src/components/Sidebar/NewThemeSettings.js
  assets/src/components/fromThemeOptions/fromThemeOptions.js
  assets/src/components/withDefaultLabel/withDefaultLabel.js
Labels: Review, [Test Env] umbriel

#673 PLANET-6239 Fix block alignment issues in the editor
  assets/src/styles/blocks/SocialMedia/SocialMediaEditorStyle.scss
  webpack.config.js
Labels: Review, UAT Passed, [Test Env] rhea

#674 Use accurates names for different types of theme settings in UI and code
  assets/src/components/Sidebar/CampaignSidebar.js
  assets/src/components/Sidebar/LocalThemeSettings.js
  assets/src/components/Sidebar/ThemeSettings.js
Labels: [Test Env] nix

#676 Bump use-theme-editor package
  package-lock.json
  package.json
Labels: [Test Env] tavros

#677 Prevent rare crash where block is null
  assets/src/BlockEditorValidation.js
Labels: Review, [Test Env] uranus

#678 PLANET-6288: Fix Share buttons on EN Form beta
  assets/src/blocks/ENForm/ENFormBlock.js
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  assets/src/components/ShareButtons/ShareButtons.js
  assets/src/components/ShareButtons/SvgIcon.js
  classes/blocks/class-enform.php
  classes/class-loader.php
Labels: [Test Env] nix

#661 PLANET-6223 Implement Google's Consent Mode on Planet 4
  assets/src/blocks/Cookies/CookiesFrontend.js
  classes/class-loader.php
Labels: Review, UAT Passed, [Test Env] iocaste

#684 Check version and conditionally use new filter introduced in 5.8
  classes/class-loader.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] mars

#682 PLANET-6307 Replace WP 5.8 deprecations
  planet4-gutenberg-blocks.php
Labels: DO NOT MERGE, Review

#686 PLANET-6225 Fix source maps for generated CSS variables
  package-lock.json
  package.json
Labels: Review, [Test Env] mars
