Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-09, with the labels that each got.

#937 PLANET-6890 Add option to hide page title in Actions
  assets/src/components/HidePageTitle/HidePageTitle.js
  assets/src/components/Sidebar/ActionSidebar.js
Labels: Review, UAT Passed, [Test Env] telesto

#939 PLANET-6859 Fix undefined description in EN form
  assets/src/blocks/ENForm/ENFormFrontend.js
Labels: Review, [Test Env] titan

#941 Upgrade React DOM to version 18
  package-lock.json
  package.json
Labels: Review, [Test Env] telesto

#944 Small CSS fixes for image hover buttons
  assets/src/styles/blocks/ColumnsEditor.scss
  assets/src/styles/blocks/TakeActionBoxout/edit.scss
  assets/src/styles/components/ImageHoverButtons.scss
  assets/src/styles/editorStyle.scss
Labels: Review, [Test Env] oberon

#940 Maintenance: Implement the ability to abort API fetch requests
  assets/src/blocks/Articles/useArticlesFetch.js
  assets/src/blocks/Covers/useCovers.js
  assets/src/blocks/Gallery/useGalleryImages.js
  assets/src/functions/getAbortController.js
Labels: Review, [Test Env] pandora
