Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-07, with the labels that each got.

#882 PLANET-6825: Page creation UI integration
  classes/patterns/class-blankpage.php
  classes/patterns/class-block-pattern.php
Labels: Review, [Test Env] sinope, [Test Env] pandora

#883 Add title placeholder param to some patterns
  classes/patterns/class-issues.php
  classes/patterns/class-quicklinks.php
  classes/patterns/class-sideimagewithtextandcta.php
Labels: Review

#885 Remove lightbox and image captions in patterns
  classes/patterns/class-highlightedcta.php
  classes/patterns/class-issues.php
  classes/patterns/class-realitycheck.php
Labels: Review, [Test Env] neptune

#890 Add coversV2 deprecated file to Covers block
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/deprecated/coversV2.js
  classes/blocks/class-covers.php
Labels: [Test Env] janus

#891 Rename Pages patterns category to Layouts
  classes/class-loader.php
  classes/patterns/class-blankpage.php
  classes/patterns/class-getinformed.php
Labels: Review, [Test Env] sinope

#892 Change the order of the Cover's deprecated versions
  assets/src/blocks/Covers/CoversEditorScript.js
Labels: [Test Env] pandora

#889 PLANET-6817 Add hover zoom effect to images in Stretched links
  assets/src/variations/stretched-link/index.scss
Labels: Review, UAT Passed, [Test Env] oberon

#893 Create specs to patterns
  tests/acceptance/PatternsCept.php
Labels: Review, [Test Env] proteus

#887 Fix block loop detection
  classes/blocks/class-blocklist.php
Labels: [Test Env] leda

#894 PLANET-6850 Add allow-plugns config to composer
  composer.json
Labels: Review, [Test Env] mars

#900 Update carousel header styles
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
Labels: Review, UAT Passed, [Test Env] neptune

#903 Add title_placeholder param to Deep Dive and Highlighted CTA patterns
  classes/patterns/class-deepdive.php
  classes/patterns/class-highlightedcta.php
Labels: Review, [Test Env] rhea

#901 Add background_color param to Side Image with Text and CTA
  classes/patterns/class-sideimagewithtextandcta.php
Labels: Review, [Test Env] deimos

#904 Add background color param to Quick Links pattern
  classes/patterns/class-quicklinks.php
Labels: Review

#906 Add background color param to Deep Dive
  classes/patterns/class-deepdive.php
Labels: Review, [Test Env] mars

#911 Fix gravity forms wp name
  classes/patterns/templates/class-twocolumnsgravityforms.php
Labels: [Test Env] tavros

#912 Use TwoColumnsGravityForms template in Get Informed
  classes/patterns/class-getinformed.php
Labels: Review
