Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-10, with the labels that each got.

#936 PLANET-6862: Enable reusable blocks for editors
  classes/controller/menu/class-blocks-usage-controller.php
  classes/controller/menu/class-reusable-blocks-controller.php
  classes/controller/menu/class-settings-controller.php
Labels: Review, [Test Env] saturn

#952 PLANET-5872 Run a11y against test instances
  .circleci/config.yml
Labels: Review

#951 PLANET-6843 Added a block filter to enforce "AJAX" toggle setting enabled by default on GF block.
  assets/src/BlockFilters.js
Labels: Review, [Test Env] sinope

#942 PLANET-6901 Move Page Header metabox fields to sidebar
  assets/src/components/Sidebar/ActionSidebar.js
  assets/src/components/Sidebar/CampaignThemeSidebar.js
  assets/src/components/Sidebar/PageHeaderSidebar.js
  assets/src/components/SidebarFields/CheckboxSidebarField.js
  assets/src/components/SidebarFields/ImageSidebarField.js
  assets/src/components/SidebarFields/TextSidebarField.js
  assets/src/components/SidebarFields/TextareaSidebarField.js
  assets/src/setupCustomSidebar.js
Labels: Review, UAT Passed, [Test Env] tavros

#955 Remove theme-editor
  assets/src/styles/themeEditor.scss
  assets/src/themeEditorIndex.js
  classes/class-loader.php
  package-lock.json
  package.json
  webpack.config.js
Labels: Review, [Test Env] oberon

#956 PLANET-6872 Add margins to Media & Text core block
  assets/src/styles/blocks/core-overrides/BlockSpacing.scss
Labels: Review, UAT Passed, [Test Env] pandora

#957 PLANET-4444 Add action button text to Action sidebar
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/components/Sidebar/ActionSidebar.js
  classes/blocks/class-covers.php
  classes/blocks/class-takeactionboxout.php
Labels: Review, UAT Passed, [Test Env] titan

#958 Fix translation function import order
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
Labels: Review, [Test Env] phoebe

#959 Fix Carousel Header focal points
  assets/src/blocks/CarouselHeader/SlideBackground.js
  classes/patterns/templates/class-carouselheader.php
Labels: Review, [Test Env] janus

#954 PLANET-6900 Add Open Graph fields to the sidebar
  assets/src/components/Sidebar/ActionSidebar.js
  assets/src/components/Sidebar/OpenGraphSidebar.js
  assets/src/components/Sidebar/PageHeaderSidebar.js
  assets/src/components/Sidebar/getSidebarFunctions.js
  assets/src/components/SidebarFields/ImageSidebarField.js
  assets/src/setupCustomSidebar.js
Labels: Review, UAT Passed, [Test Env] mars
