Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-11, with the labels that each got.

#965 PLANET-6951: Implement new filter hook applied to query pagination
  planet4-gutenberg-blocks.php
Labels: [Test Env] pandora

#967 Simplify Ci config
  .circleci/config.yml
Labels: Review, [Test Env] phoebe

#968 PLANET-6947 Use checkboxes for tags selection
  assets/src/components/TermSelector/TermSelector.js
  assets/src/replaceTaxonomyTermSelectors.js
Labels: Review, UAT Passed, [Test Env] janus

#970 PLANET-6939 Convert Quick Links pattern into a block template
  assets/src/block-templates/quick-links/block.json
  assets/src/block-templates/quick-links/index.js
  assets/src/block-templates/quick-links/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-action.php
  classes/patterns/class-deepdivetopic.php
  classes/patterns/class-getinformed.php
  classes/patterns/class-highleveltopic.php
  classes/patterns/class-quicklinks.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] telesto

#971 PLANET-6940 Convert Deep Dive pattern into a block template
  assets/src/block-templates/deep-dive/block.json
  assets/src/block-templates/deep-dive/index.js
  assets/src/block-templates/deep-dive/template.js
  assets/src/block-templates/quick-links/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-deepdive.php
  classes/patterns/class-deepdivetopic.php
  classes/patterns/class-highleveltopic.php
  classes/patterns/class-takeaction.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] oberon
