Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-03, with the labels that each got.

#801 PLANET-6657 Fix CarouselHeader RTL slide transitions
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
Labels: Review, [Test Env] umbriel

#805 Fix entire classic block content used for Anchor
  assets/src/blocks/Submenu/getHeadingsFromBlocks.js
Labels: Review, [Test Env] atlas

#806 Unwrap Carousel Header CSS
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
Labels: [Test Env] sinope

#810 PLANET-6658 Fix WPML RTL mayhem
  planet4-gutenberg-blocks.php
Labels: [Test Env] oberon

#807 PLANET-6654 Fix editor previews
  assets/src/blocks/Columns/example.js
  assets/src/blocks/Covers/example.js
  assets/src/blocks/Submenu/example.js
  assets/src/styles/editorStyle.scss
  classes/blocks/class-base-block.php
  classes/blocks/class-covers.php
Labels: Review, [Test Env] sinope, [Test Env] phobos

#813 Prepare for features in new classes
  classes/class-loader.php
  classes/controller/menu/class-en-settings-controller.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] titan

#817 PLANET-6668 Remove dark green color from palette and lightbox from icon
  classes/class-loader.php
  classes/patterns/class-highlightedcta.php
Labels: Review, UAT Passed

#815 PLANET-6667 Create Reality Check block pattern
  classes/patterns/class-block-pattern.php
  classes/patterns/class-realitycheck.php
Labels: Review, UAT Passed, [Test Env] titan
