Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-12, with the labels that each got.

#980 PLANET-6980 Make sure non-admins cannot create new tags in the sidebar
  assets/src/components/TermSelector/TermSelector.js
Labels: Review, [Test Env] umbriel

#977 PLANET-6981 Remove jQuery from addButtonLinkPasteWarning
  assets/src/addButtonLinkPasteWarning.js
Labels: Review, [Test Env] iocaste

#986 PLANET-6960 Add sidebar option to define canonical link
  assets/src/components/Sidebar/SearchEngineOptimizationsSidebar.js
  assets/src/setupCustomSidebar.js
Labels: Review, UAT Passed, [Test Env] umbriel
