Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-08, with the labels that each got.

#909 Add alignfull param to Side Image with Text & CTA
  classes/patterns/class-sideimagewithtextandcta.php
Labels: Review, [Test Env] iocaste

#907 Fix Media & Text block padding
  assets/src/styles/blocks/core-overrides/_media-text.scss
Labels: Review, UAT Passed, [Test Env] titan

#908 Override pagination native functionality
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] janus

#860 PLANET-6680: Page Header block pattern
  .stylelintrc
  assets/src/blocks/PageHeader/PageHeaderBlock.js
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/PageHeader.scss
  classes/class-loader.php
  classes/patterns/class-block-pattern.php
  classes/patterns/class-pageheader.php
  classes/patterns/class-pageheaderimgleft.php
Labels: Review, UAT needed, [Test Env] telesto

#884 PLANET-6524: New homepage block pattern
  classes/patterns/class-block-pattern.php
  classes/patterns/class-homepage.php
  classes/patterns/templates/class-carouselheader.php
Labels: Review, UAT Passed, [Test Env] phobos

#914 PLANET-6768: Update issues pattern
  assets/src/styles/blocks.scss
  classes/patterns/class-issues.php
Labels: Review, UAT Passed, [Test Env] rhea

#919 Remove custom padding classes from some core blocks
  admin/js/editor.js
  assets/src/styles/blocks.scss
  classes/patterns/class-action.php
Labels: Review, [Test Env] titan

#902 PLANET-6737 Implement High-Level Topic pattern layout
  classes/patterns/class-block-pattern.php
  classes/patterns/class-highleveltopic.php
Labels: Review, UAT Passed, [Test Env] leda

#918 Create GravityFormWithImage template
  classes/patterns/class-action.php
  classes/patterns/class-getinformed.php
  classes/patterns/class-homepage.php
  classes/patterns/templates/class-gravityformwithimage.php
  classes/patterns/templates/class-gravityformwithtext.php
Labels: [Test Env] tavros

#920 Use new GravityFormWithText template in High Level Topic
  classes/patterns/class-highleveltopic.php
Labels: Review, [Test Env] janus

#922 Add title_placeholder param to Covers template
  classes/patterns/class-highleveltopic.php
  classes/patterns/templates/class-covers.php
Labels: Review, [Test Env] phoebe

#921 Add title_placeholder param to PageHeader pattern
  classes/patterns/class-highleveltopic.php
  classes/patterns/class-pageheader.php
Labels: Review, [Test Env] phobos

#927 Refactor Covers template
  classes/patterns/class-action.php
  classes/patterns/class-homepage.php
  classes/patterns/templates/class-covers.php
Labels: Review, [Test Env] umbriel

#924 PLANET-6738: Deep Dive Topic pattern
  classes/patterns/class-block-pattern.php
  classes/patterns/class-deepdivetopic.php
  tests/acceptance/PatternsCept.php
Labels: UAT Passed, [Test Env] nix

#926 Add grey background color to PageHeader pattern
  classes/patterns/class-pageheader.php
Labels: Review, [Test Env] saturn

#917 PLANET-6528 Implement Campaign pattern layout
  classes/patterns/class-block-pattern.php
  classes/patterns/class-campaign.php
Labels: Review, UAT Passed, [Test Env] mars

#928 PLANET-6676 Update proper textdomain name in JS files
  assets/src/BlockEditorValidation.js
  assets/src/blocks/Accordion/AccordionEditorScript.js
  assets/src/blocks/Articles/ArticlePreview.js
  assets/src/blocks/Articles/ArticlesBlock.js
  assets/src/blocks/Columns/ColumnsBlock.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/blocks/Counter/CounterBlock.js
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Gallery/GalleryBlock.js
  assets/src/blocks/GuestBook/GuestBookBlock.js
  assets/src/blocks/ShareButtons/ShareButtonsBlock.js
  assets/src/blocks/SocialMedia/SocialMediaBlock.js
  assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
  assets/src/blocks/Submenu/SubmenuLevel.js
  assets/src/blocks/Timeline/TimelineBlock.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
  assets/src/components/ShareButtons/ShareButtons.js
  classes/class-loader.php
Labels: DO NOT MERGE, Review

#923 PLANET-6828 Use Bootstrap for Covers carousel layout
  assets/src/blocks/Covers/CoversCarouselControls.js
  assets/src/blocks/Covers/CoversCarouselLayout.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Covers/CoversFrontend.js
  assets/src/blocks/Covers/CoversIcon.js
  assets/src/blocks/Covers/useCovers.js
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/styles/blocks/Covers/layouts/CoversCarouselLayout.scss
  assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
  assets/src/styles/blocks/Covers/styles/ContentCovers.scss
  assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
Labels: Review, UAT Passed, [Test Env] pluto
