Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-04, with the labels that each got.

#821 PLANET-6667 Increase Reality Check pattern spacer height
  classes/patterns/class-realitycheck.php
Labels: Review

#816 Remove EN form auth public endpoint
  assets/src/blocks/ENForm/ENFormFrontend.js
  classes/rest/class-rest-api.php
Labels: Review, [Test Env] venus

#820 PLANET-6670 Use core class for full alignment
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  assets/src/blocks/Happypoint/HappypointFrontend.js
  assets/src/blocks/HubspotForm/HubspotFormEditor.js
  assets/src/blocks/HubspotForm/HubspotFormFrontend.js
  assets/src/blocks/Splittwocolumns/SplittwocolumnsFrontend.js
  assets/src/blocks/Splittwocolumns/SplittwocolumnsInPlaceEdit.js
  assets/src/styles/blocks/HubspotForm/HubspotFormStyles.scss
  assets/src/styles/blocks/WideBlocks.scss
  templates/blocks/carousel_header_full-width-classic.twig
  templates/blocks/enform.twig
  templates/blocks/enform/enblock.twig
Labels: Review, [Test Env] phobos

#795 PLANET-6612 Whitelist the articles block in Post
  assets/src/blocks/Articles/ArticlesEditor.js
  classes/blocks/class-articles.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] jupiter

#812 PLANET-6627 Add block template with 2 blocks(paragraph and articles block) for pagetype post
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] rhea

#824 Fix slider not full width in editor
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderEditorStyle.scss
Labels: [Test Env] venus

#796 Ensure class is not needed to use style
  assets/src/styles/blocks/Articles.scss
Labels: Review, [Test Env] mars

#825 PLANET-6690 Remove Table block overrides
  assets/src/BlockFilters.js
  assets/src/components/p4_table/edit.js
  assets/src/components/p4_table/state.js
Labels: Review, [Test Env] titan

#830 PLANET-6735 Add Lightbox to Media and Text block images
  assets/src/components/Lightbox/setupLightboxForImages.js
  assets/src/styles/blocks/core-overrides/_media-text.scss
Labels: Review, [Test Env] iocaste

#827 PLANET-6731: Add filter hook for enform data
  classes/rest/class-rest-api.php
Labels: [Test Env] titan

#829 PLANET-6734 Remove blocks heading links style overrides
  assets/src/styles/blocks/Articles.scss
  assets/src/styles/blocks/Columns.scss
Labels: Review, [Test Env] venus

#834 PLANET-6740 Limit Lightbox pointer cursor to img
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review, [Test Env] iocaste

#835 Add Query and Query pagination to post report
  classes/controller/menu/class-blocks-usage-controller.php
Labels: Review

#777 Update Card's width from Covers for XXL viewports
  assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
  assets/src/styles/blocks/Covers/styles/ContentCovers.scss
  assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
Labels: Review, UAT Passed, [Test Env] proteus

#837 PLANET-6742 Add right sizes attributes for some core blocks
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] oberon
