Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-02, with the labels that each got.

#775 PLANET-6598: Fix carousel Layout excessive width of cards from Covers
  assets/src/styles/blocks/Covers/styles/ContentCovers.scss
  assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
Labels: Review, [Test Env] proteus

#769 PLANET-6502 Rename "Columns" to "Planet 4 Columns" and add core Columns block
  assets/src/blocks/Columns/ColumnsBlock.js
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] rhea

#780 PLANET-6594 Enable core WP "Media & Text" block
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] nix

#493 PLANET-6634: Experimentation on block usage report
  classes/controller/menu/class-blocks-usage-controller.php
  classes/search/block/class-blockusage.php
  classes/search/block/class-blockusagetable.php
  classes/search/block/class-query.php
  classes/search/block/query/class-parameters.php
  classes/search/block/sql/class-regex.php
  classes/search/block/sql/class-sqlquery.php
  classes/search/class-blocksearch.php
Labels: [Test Env] atlas

#785 Dev toggle for all blocks
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] tavros

#781 PLANET-6496: HappyPoint override and default content
  assets/src/blocks/Happypoint/EmbedCodeHelp.js
  assets/src/blocks/Happypoint/HappyPointConstants.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Happypoint/HappypointFrontend.js
  assets/src/blocks/Happypoint/MailingListIframeHelp.js
  assets/src/blocks/Happypoint/OverrideFormHelp.js
  assets/src/blocks/Happypoint/deprecated/HappyPointV1.js
  classes/blocks/class-happypoint.php
Labels: [Test Env] pluto

#791 PLANET-6515 Add Allowed blocks in action page type
  planet4-gutenberg-blocks.php
Labels: Review

#793 Add Media and Text code block to blocks usage report
  classes/controller/menu/class-blocks-usage-controller.php
Labels: Review, [Test Env] mars

#779 PLANET-6075 Always enable necessary cookies
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/blocks/Cookies/useCookie.js
  assets/src/styles/blocks/Cookies.scss
Labels: Review, UAT Passed

#786 PLANET-6635: Fix missing EN Form custom donate URL
  assets/src/blocks/ENForm/ENFormSettings.js
  classes/blocks/class-enform.php
  tests/acceptance/ENFormCest.php
Labels: [Test Env] pluto

#798 PLANET-6650 Remove uniqueId from Happypoint instance id
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Happypoint/HappypointFrontend.js
  assets/src/blocks/Happypoint/deprecated/HappyPointV1.js
  assets/src/blocks/Happypoint/useHubspotEmbedCode.js
Labels: Review, [Test Env] pluto

#799 Hide Cookies block checkbox when name and description are spaces
  assets/src/blocks/Cookies/CookiesFrontend.js
Labels: Review, [Test Env] umbriel

#789 PLANET-6616 Create new block pattern: side image with text and CTA
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/core-overrides/_media-text.scss
  classes/class-loader.php
  classes/patterns/class-block-pattern.php
  classes/patterns/class-sideimagewithtextandcta.php
  planet4-gutenberg-blocks.php
Labels: Review, UAT Passed, [Test Env] atlas
