Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-06, with the labels that each got.

#861 Fix reusable block loop on parsing
  classes/blocks/class-blocklist.php
Labels: [Test Env] sinope

#865 PLANET-6778 Add spacing to core Group block
  assets/src/styles/blocks/core-overrides/BlockSpacing.scss
  assets/src/styles/editorStyle.scss
Labels: Review, UAT Passed, [Test Env] deimos

#867 Enforce hiding Image block caption with CSS
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review

#828 PLANET-6534 Create Deep Dive block pattern
  classes/patterns/class-block-pattern.php
  classes/patterns/class-deepdive.php
Labels: Review, UAT Passed, [Test Env] nix

#869 PLANET-6340 Add lazy loading to Take Action covers
  assets/src/blocks/Covers/TakeActionCovers.js
Labels: Review, [Test Env] janus

#831 PLANET-6520: Implement Quick Links block pattern
  assets/src/styles/blocks/core-overrides/_columns.scss
  classes/patterns/class-block-pattern.php
  classes/patterns/class-quicklinks.php
Labels: Review, UAT Passed, [Test Env] neptune

#872 PLANET-6617 Implement resize handler for Covers block carousel
  assets/src/blocks/Covers/CoversFrontend.js
Labels: Review, [Test Env] pandora

#876 Add Pages block pattern category
  classes/class-loader.php
Labels: Review

#875 PLANET-6827 Parse HTML tags in EN form fields
  assets/src/blocks/ENForm/ENFormFrontend.js
Labels: Review, [Test Env] titan

#868 PLANET-6816: Pull pages for covers manual override
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/components/PostSelector/PostSelector.js
  classes/blocks/class-covers.php
  classes/rest/class-published.php
  classes/rest/class-rest-api.php
Labels: [Test Env] tavros

#873 PLANET-6781: Block report - pagination, block style, api
  classes/controller/menu/class-blocks-usage-controller.php
  classes/search/block/class-blockusage.php
  classes/search/block/class-blockusageapi.php
  classes/search/block/class-blockusagetable.php
Labels: [Test Env] saturn

#880 Fix deprecated wp.editor elements console warnings
  assets/src/ImageBlockExtension.js
  assets/src/blocks/Counter/CounterEditor.js
Labels: Review

#870 PLANET-6723: Enable articles in posts
  planet4-gutenberg-blocks.php
Labels: Review, UAT Passed, [Test Env] oberon
