Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-05, with the labels that each got.

#842 Add Rounded style to Image block
  admin/js/editor.js
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review, [Test Env] tavros

#844 PLANET-6771 Remove duplicate EN Form CSS
  assets/src/styles/blocks.scss
Labels: Review, [Test Env] tavros

#811 PLANET-6638: Issues block pattern
  admin/js/editor.js
  assets/src/styles/blocks.scss
  classes/patterns/class-block-pattern.php
  classes/patterns/class-issues.php
Labels: Review, UAT Passed, [Test Env] sinope

#846 Fix undefined mediaId value in core/media-text block when the media is not set
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] saturn

#845 PLANET-4993 Remove EN Form font families
  assets/src/styles/blocks/ENForm/campaigns/_mixins.scss
  assets/src/styles/blocks/ENForm/components/_enform.scss
Labels: Review, [Test Env] tavros

#852 PLANET-6686: Fix Split two columns issue/tag types
  assets/src/blocks/Splittwocolumns/SplittwocolumnsSettings.js
  assets/src/styles/blocks/SplitTwoColumns.scss
  assets/src/styles/blocks/SplitTwoColumnsEditor.scss
Labels: [Test Env] tavros

#851 PLANET-6700: Fix broken arrows for Gallery and Cover blocks
  assets/src/styles/blocks/CarouselHeader/CarouselHeaderStyle.scss
  assets/src/styles/blocks/Covers/layouts/CoversCarouselLayout.scss
  assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
Labels: [Test Env] sinope

#838 Block report: Parse inner blocks data
  classes/search/block/class-blockusage.php
Labels: [Test Env] rhea

#843 Add chevron style to heading core block
  admin/js/editor.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/core-overrides/Heading.scss
  assets/src/styles/blocks/core-overrides/HeadingEditor.scss
  assets/src/styles/editorStyle.scss
Labels: Review, UAT Passed, [Test Env] deimos

#849 PLANET-6712 Add transparent style to core Button block
  admin/js/editor.js
  classes/patterns/class-highlightedcta.php
Labels: Review, UAT Passed, [Test Env] titan

#847 PLANET-6704: Insert placeholder images to patterns
  classes/patterns/class-highlightedcta.php
  classes/patterns/class-issues.php
  classes/patterns/class-realitycheck.php
  classes/patterns/class-sideimagewithtextandcta.php
Labels: Review, UAT needed, [Test Env] leda

#839 PLANET-6748: Fix read more text from Covers block
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/CoversFrontend.js
  assets/src/blocks/Covers/CoversGridLoadMoreButton.js
  classes/blocks/class-covers.php
Labels: Review, [Test Env] oberon

#855 Add Columns block on blocks usage report
  classes/controller/menu/class-blocks-usage-controller.php
Labels: Review, [Test Env] tavros

#856 Add Grey 5% to our color palette
  classes/class-loader.php
Labels: Review, [Test Env] iocaste

#857 PLANET-6638 Update Issues block pattern background color
  classes/patterns/class-issues.php
Labels: Review

#858 Force rounded images to have an aspect ratio of 1
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review, [Test Env] pluto

#859 PLANET-6788 Remove color palette
  classes/class-loader.php
Labels: Review, [Test Env] rhea

#833 Add group variation for full block link
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Editor.scss
  assets/src/styles/editorStyle.scss
  assets/src/variations/stretched-link/edit.scss
  assets/src/variations/stretched-link/index.scss
Labels: Review, UAT Passed, [Test Env] phoebe

#866 Create CSS class to force hiding Image block caption/credits
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review, UAT Passed, [Test Env] pluto

#863 Add Image block rounded styles with specific sizes
  admin/js/editor.js
  assets/src/components/Image/ImageBlockEdit.js
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review, UAT Passed, [Test Env] oberon
