Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2022-01, with the labels that each got.

#754 Remove covers ids
  assets/src/blocks/Covers/CampaignCovers.js
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Covers/example.js
  classes/blocks/class-covers.php
Labels: Review, [Test Env] titan

#756 Revert "PLANET-6503 Workaround to prevent local images CarouselHeader"
  assets/src/blocks/CarouselHeader/EditableBackground.js
  classes/class-loader.php
Labels: Review, [Test Env] phobos

#755 Use consistent attribute names for all Covers styles
  assets/src/blocks/Covers/CampaignCovers.js
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Covers/example.js
  classes/blocks/class-covers.php
Labels: Review, [Test Env] neptune

#741 PLANET-6487 Avoid discarding data in an effect
  assets/src/blocks/Covers/CoversEditor.js
Labels: Review, [Test Env] janus

#757 Make EN menu item fit in the sidebar
  admin/images/en.png
  admin/images/logo_menu_page_16x16.jpg
  classes/controller/menu/class-en-settings-controller.php
Labels: Review, [Test Env] rhea

#759 PLANET-6000 Remove Lightbox from images with links
  assets/src/components/Lightbox/setupLightboxForImages.js
Labels: Review, [Test Env] rhea

#760 Fix dataLayer declaration in ShareButtons
  assets/src/components/ShareButtons/ShareButtons.js
Labels: [Test Env] titan

#770 Remove obsolete config option
  classes/class-loader.php
Labels: Review

#764 PLANET-6496 Happy Point: Add option for code snippet embed
  assets/src/blocks/Happypoint/EmbedCodeHelp.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Happypoint/HappypointFrontend.js
  assets/src/blocks/Happypoint/useHubspotEmbedCode.js
  assets/src/components/useScript/useScript.js
  classes/blocks/class-happypoint.php
Labels: Review, [Test Env] pluto

#771 PLANET-6599: Fix arrow issue from Carousel Take Action block
  assets/src/blocks/Covers/useCovers.js
Labels: Review

#766 PLANET-6603 Use default Cookies copy in Cookies block
  assets/src/blocks/Cookies/CookiesBlock.js
  assets/src/blocks/Cookies/CookiesFieldResetButton.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/styles/blocks/CookiesEditor.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-cookies.php
  classes/class-loader.php
Labels: Review, UAT Passed
