Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-11, with the labels that each got.

#1148 PLANET-7295 Fix related articles block and block patterns report
  classes/blocks/class-blocklist.php
Labels: Review, [Test Env] janus, [Test Env] umbriel

#1151 Fix CoversScript selector
  assets/src/blocks/Covers/CoversScript.js
Labels: [Test Env] pandora

#1152 PLANET-7310: Update secondary button of Columns block
  assets/src/blocks/Columns/ColumnsTasks.js
  assets/src/styles/blocks/Columns.scss
Labels: [Test Env] pluto

#1150 PLANET-7323: Remove Lodash dependencies
  assets/src/ImageBlockExtension.js
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
  assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
  assets/src/components/ColorPaletteControl/ColorPaletteControl.js
  assets/src/components/TermSelector/TermSelector.js
  package-lock.json
  package.json
Labels: [Test Env] iocaste

#1155 PLANET-7326: Detect Carousel header in reusable block
  classes/blocks/class-carouselheader.php
  classes/blocks/class-gallery.php
Labels: [Test Env] neptune

#1154 PLANET-7318: E2E test for blocks report API endpoint
  tests/e2e/blocks-report-api.spec.js
Labels: [Test Env] phoebe

#1156 PLANET-7330 Take menu order option into account for ordering Covers block
  classes/blocks/class-covers.php
Labels: Review, [Test Env] umbriel, [Test Env] atlas

#1157 PLANET-7331: Optimize Block report queries
  classes/controller/menu/class-blocks-usage-controller.php
  classes/search/block/sql/class-like.php
  classes/search/block/sql/class-sqlquery.php
  classes/search/class-patternsearch.php
Labels: [Test Env] phobos

#1160 PLANET-7336: planet4-blocks category is registered twice
  classes/class-loader.php
Labels: [Test Env] pandora

#1161 PLANET-7297 Fix Carousel Header editor slide change
  assets/src/blocks/CarouselHeader/SidebarSlide.js
Labels: [Test Env] iocaste

#1158 PLANET-7317: E2E test for Related Articles block
  tests/e2e/env/.env.default
  tests/e2e/related-articles.spec.js
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/post.js
Labels: [Test Env] leda

#1162 PLANET-7280 Remove block variation version of the Page Header
  assets/src/block-templates/page-header/template.js
  assets/src/blocks/PageHeader/PageHeaderBlock.js
  assets/src/editorIndex.js
  assets/src/styles/blocks/PageHeader.scss
Labels: Review, [Test Env] phoebe

#1149 PLANET-7238: Update test for WP6.4
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  tests/e2e/covers-content.spec.js
  tests/e2e/tools/lib/covers.js
Labels: [Test Env] nix

#1163 PLANET-7334: Fix HappyPoint height on mobile with Recaptcha
  assets/src/styles/blocks/Happypoint.scss
Labels: [Test Env] atlas
