Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-08, with the labels that each got.

#1094 PLANET-7189 Remove our uses of ReactDOM.render
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
  assets/src/blocks/Covers/CoversScript.js
  assets/src/blocks/ENForm/ENFormScript.js
  assets/src/blocks/Gallery/GalleryBlock.js
  assets/src/blocks/Spreadsheet/SpreadsheetScript.js
  assets/src/components/Lightbox/setupLightboxForImages.js
  assets/src/frontendIndex.js
  assets/src/functions/hydrateBlock.js
Labels: Review, [Test Env] jupiter

#1089 Update Browserslist DB
  package-lock.json
Labels: [Test Env] leda

#1095 Fix broken page on gcloud 403
  classes/blocks/class-carouselheader.php
Labels: [Test Env] leda

#1096 PLANET-7215 Apply the new design to the Submenu block
  assets/src/styles/blocks/Submenu.scss
  tests/e2e/env/.env.ci
Labels: Review, UAT Passed, [Test Env] oberon

#1098 PLANET-7217 Fix carousel header flicker issue
  assets/src/blocks/CarouselHeader/CarouselControls.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/CarouselHeader/Sidebar.js
  assets/src/blocks/CarouselHeader/SidebarSlide.js
  assets/src/blocks/CarouselHeader/useSlides.js
Labels: [Test Env] telesto

#1085 Adjust code regarding the new design tokens
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/Columns/ColumnsFrontend.js
  assets/src/blocks/Covers/CoversFrontend.js
  assets/src/blocks/Gallery/GalleryFrontend.js
  assets/src/blocks/Media/MediaFrontend.js
  assets/src/blocks/SocialMedia/SocialMediaFrontend.js
  assets/src/blocks/Timeline/TimelineFrontend.js
Labels: UAT Passed, [Test Env] pandora

#1106 Fix hydrateBlock method
  assets/src/functions/hydrateBlock.js
Labels: [Test Env] umbriel

#1103 PLANET-6855: Add covers thumbnail size for large screen
  assets/src/blocks/Columns/Columns.js
  assets/src/blocks/Columns/imageSizes.js
  assets/src/blocks/Covers/imageSizes.js
  classes/blocks/class-columns.php
Labels: [Test Env] leda

#969 PLANET-6927: Fix Page Header spacing issue
  assets/src/components/Parallax/setupParallax.js
  assets/src/styles/blocks/PageHeader.scss
Labels: [Test Env] pluto

#1110 Update Playwright version
  .circleci/config.yml
  package-lock.json
  package.json
Labels: [Test Env] titan
