Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-03, with the labels that each got.

#1017 PLANET-7087 Remove old blocks report
  classes/controller/menu/class-blocks-usage-controller.php
  classes/search/block/class-blockusageapi.php
  classes/search/block/class-blockusagetable.php
Labels: Review, [Test Env] pandora

#932 PLANET-6874: Fix the Gallery block
  assets/src/blocks/Gallery/GalleryBlock.js
  assets/src/blocks/Gallery/GalleryCarousel.js
  assets/src/blocks/Gallery/GalleryFrontend.js
  assets/src/blocks/Gallery/GalleryGrid.js
  assets/src/blocks/Gallery/GalleryScript.js
  assets/src/blocks/Gallery/GalleryThreeColumns.js
  assets/src/components/Lightbox/Lightbox.js
  assets/src/components/Lightbox/useLightbox.js
  assets/src/functions/hydrateBlock.js
  classes/blocks/class-base-block.php
  classes/blocks/class-gallery.php
Labels: Review, [Test Env] nix

#1020 Small improvements for Columns Tasks on mobile/tablet
  assets/src/blocks/Columns/ColumnsTasks.js
  assets/src/styles/blocks/Accordion/AccordionStyle.scss
  assets/src/styles/blocks/Columns.scss
Labels: Review, UAT needed, [Test Env] phoebe

#1025 Remove stretched link edit styles from frontend
  assets/src/styles/blocks.scss
Labels: Review, [Test Env] janus
