Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-07, with the labels that each got.

#1069 PLANET-7084 Convert Take Action pattern layout into a Block Template
  assets/src/block-templates/take-action/block.json
  assets/src/block-templates/take-action/index.js
  assets/src/block-templates/take-action/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-takeaction.php
  planet4-gutenberg-blocks.php
Labels: Review

#1075 PLANET-5423 Add Playwright test for Spreadsheet block
  tests/e2e/spreadsheet.spec.js
Labels: Review, [Test Env] atlas

#1079 Expand eslint check on all js code
  .circleci/config.yml
  admin/js/editor.js
  admin/js/enforms.js
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/blocks/ENForm/FormGenerator.js
  tests/e2e/enform.spec.js
  tests/e2e/fixtures/enform/enformData.js
  tests/e2e/take-action-boxout.spec.js
  tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
  tests/e2e/tools/lib/rest.js
Labels: Review, [Test Env] deimos

#1081 PLANET-7078 Convert Action pattern layout into a Block Template
  assets/src/block-templates/action/block.json
  assets/src/block-templates/action/index.js
  assets/src/block-templates/action/template.js
  assets/src/block-templates/template-list.js
  assets/src/block-templates/templates/gravity-form-with-text.js
  classes/patterns/class-action.php
  classes/patterns/class-deepdivetopic.php
  planet4-gutenberg-blocks.php
Labels: Review

#1082 PLANET-7169 Fix deprecated value bug in analytics field
  assets/src/components/Sidebar/AnalyticsTrackingSidebar.js
  classes/rest/class-rest-api.php
Labels: Review, UAT Passed

#1087 PLANET-7081 Convert Get Informed pattern layout to block template
  assets/src/block-templates/get-informed/block.json
  assets/src/block-templates/get-informed/index.js
  assets/src/block-templates/get-informed/template.js
  assets/src/block-templates/homepage/template.js
  assets/src/block-templates/issues/block.json
  assets/src/block-templates/issues/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-getinformed.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] telesto

#1088 PLANET-7080 Convert High Level Topic layout into a Block Template
  assets/src/block-templates/deep-dive-topic/template.js
  assets/src/block-templates/high-level-topic/block.json
  assets/src/block-templates/high-level-topic/index.js
  assets/src/block-templates/high-level-topic/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-highleveltopic.php
  classes/patterns/templates/class-carouselheader.php
  classes/patterns/templates/class-covers.php
  classes/patterns/templates/class-gravityformwithtext.php
  classes/patterns/templates/class-templatepattern.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] phoebe

#1080 PLANET-5419 Add Playwright test for Articles block
  tests/e2e/articles.spec.js
Labels: Review

#1091 Fix act_page notices
  classes/blocks/class-covers.php
Labels: [Test Env] telesto
