Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-05, with the labels that each got.

#1044 PLANET-7138: Remove text shadows on links
  assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
  assets/src/styles/blocks/SplitTwoColumns.scss
Labels: Review, UAT Passed, [Test Env] proteus

#1051 Implement missing hover styles to the SplitTwoColumns block
  assets/src/styles/blocks/SplitTwoColumns.scss
Labels: [Test Env] neptune

#1039 PLANET-7129: Change the import of the ServerSideRender function
  assets/src/blocks/SocialMediaCards/SocialMediaCards.js
  assets/src/blocks/SubPages/SubPages.js
Labels: Review, [Test Env] atlas

#1041 PLANET-7063 Re-write the Editor Selector test in Playwright
  tests/e2e/editor-selector.spec.js
Labels: Review, [Test Env] deimos

#1038 PLANET-7070 Re-write the Page Layouts Modal test in Playwright
  tests/acceptance/PatternsCept.php
  tests/e2e/page-layouts-modal.spec.js
Labels: Review, [Test Env] janus

#1043 Standarize the import/destructure of the WP's block editor package
  assets/src/block-templates/edit.js
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/blocks/Counter/CounterEditor.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Gallery/GalleryEditor.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  assets/src/blocks/SocialMediaCards/SocialMediaCards.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
Labels: Review, [Test Env] iocaste

#1053 PLANET-7071 Rewrite Take Action Boxout test in Playwright
  tests/acceptance/TakeActionBoxoutCept.php
  tests/e2e/editor-selector.spec.js
  tests/e2e/page-layouts-modal.spec.js
  tests/e2e/take-action-boxout.spec.js
  tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
  tests/e2e/tools/lib/login.js
  tests/e2e/tools/lib/new-post.js
  tests/e2e/tools/lib/nonce.js
  tests/e2e/tools/lib/rest.js
Labels: Review, [Test Env] deimos

#1057 Adjust test user trigger to new instance parameter
  .circleci/config.yml
Labels: Review, [Test Env] sinope

#1054 PLANET-7065 Re-write the Carousel Header test in Playwright
  .eslintrc.json
  tests/acceptance/CarouselHeaderClassicCept.php
  tests/e2e/carousel-header.spec.js
Labels: Review, [Test Env] janus
