Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-09, with the labels that each got.

#1105 Refactor GuestBook block
  assets/src/blocks/GuestBook/GuestBookBlock.js
  assets/src/blocks/GuestBook/GuestBookEditorScript.js
  assets/src/blocks/GuestBook/GuestBookFrontend.js
  assets/src/blocks/GuestBook/GuestBookScript.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  classes/blocks/class-guestbook.php
  webpack.config.js
Labels: Review, [Test Env] phoebe

#1111 PLANET-7242: Fix title text covered by background
  assets/src/styles/blocks/PageHeader.scss
Labels: [Test Env] leda

#1117 PLANET-7252: Incorrect typeface used for caption in Gallery Carousel block
  assets/src/styles/blocks/Gallery/styles/GalleryCarousel.scss
Labels: [Test Env] rhea

#1115 Disable Split Two Columns blocks on new IA
  planet4-gutenberg-blocks.php
  tests/e2e/split-two-columns.spec.js
Labels: Review, [Test Env] pluto

#1121 Use requested post types in block count
  classes/search/block/class-blockusage.php
  classes/search/block/class-blockusageapi.php
Labels: [Test Env] phoebe

#1116 Pattern report is missing template usage
  classes/search/class-patternsearch.php
  classes/search/pattern/class-patternusage.php
Labels: [Test Env] pandora

#1124 Fix Split Two Columns folder name case
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsFrontend.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsSettings.js
  assets/src/blocks/SplitTwoColumns/deprecated/splitTwoColumnsV1.js
  assets/src/blocks/SplitTwoColumns/imageSizes.js
  assets/src/blocks/SplitTwoColumns/register.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
Labels: Review, [Test Env] phobos

#1050 PLANET-6958: Remove deprecated multiline prop
  assets/src/blocks/Accordion/AccordionEditor.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/CarouselHeader/Caption.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Columns/EditableColumns.js
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/blocks/Counter/CounterEditor.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
  assets/src/blocks/Gallery/GalleryEditor.js
  assets/src/blocks/Media/MediaEditor.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
Labels: Review, [Test Env] phoebe

#1126 Fix Split Two Columns components name case
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsFrontend.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsInPlaceEdit.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsSettings.js
  assets/src/blocks/SplitTwoColumns/register.js
  assets/src/frontendIndex.js
Labels: Review, [Test Env] pandora

#1125 PLANET-7256 Refactor post Post Types selector
  assets/src/components/AssignOnlyFlatTermSelector/AssignOnlyFlatTermSelector.js
  assets/src/replaceTaxonomyTermSelectors.js
Labels: Review, [Test Env] atlas

#1127 Split files for Split Two Columns block
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsBlock.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditorScript.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsScript.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/SplitTwoColumns/SplitTwoColumnsEditorStyle.scss
  assets/src/styles/blocks/SplitTwoColumns/SplitTwoColumnsStyle.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-splittwocolumns.php
  tests/e2e/env/.env.ci
  webpack.config.js
Labels: Review, [Test Env] nix

#1129 Fix Split Two Columns editor component
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
Labels: [Test Env] rhea

#1130 Fix E2E flaky tests failing CI job
  playwright.config.js
  tests/e2e/env/.env.ci
  tests/e2e/env/.env.default
Labels: [Test Env] phoebe

#1133 Remove autop wrapped function
  assets/src/blocks/ENForm/ENFormInPlaceEdit.js
Labels: Review, [Test Env] atlas

#1134 Fix Columns block src set console warnings
  assets/src/blocks/Columns/Columns.js
Labels: Review, [Test Env] phoebe

#1112 PLANET-7197: Adapt block loading order
  classes/blocks/class-accordion.php
  classes/blocks/class-carouselheader.php
  classes/blocks/class-enform.php
  classes/blocks/class-gallery.php
  classes/blocks/class-guestbook.php
  classes/blocks/class-socialmedia.php
  classes/blocks/class-spreadsheet.php
  classes/blocks/class-takeactionboxout.php
  classes/blocks/class-timeline.php
  classes/class-loader.php
  tests/e2e/spreadsheet.spec.js
Labels: [Test Env] saturn
