Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-12, with the labels that each got.

#1165 PLANET-7312 Remove the old ENForm code
  assets/src/styles/blocks/OldENForm/campaigns/_mixins.scss
  assets/src/styles/blocks/OldENForm/campaigns/themes/_theme_climate.scss
  assets/src/styles/blocks/OldENForm/components/_enform-full-width-bg.scss
  assets/src/styles/blocks/OldENForm/components/_enform-full-width.scss
  assets/src/styles/blocks/OldENForm/components/_enform-side-style.scss
  assets/src/styles/blocks/OldENForm/components/_enform.scss
Labels: Review, [Test Env] iocaste

#1168 Split Cookies Block files
  assets/src/blocks/Cookies/CookiesBlock.js
  assets/src/blocks/Cookies/CookiesEditorScript.js
  assets/src/blocks/Cookies/CookiesScript.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Cookies/Cookies.scss
  assets/src/styles/blocks/Cookies/CookiesEditor.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-cookies.php
  webpack.config.js
Labels: Review, [Test Env] pandora

#1167 PLANET-7237 Apply the Design tokens font-family & font-size on certain blocks
  assets/src/blocks/Cookies/CookiesFrontend.js
  assets/src/styles/blocks/Columns.scss
  assets/src/styles/blocks/ColumnsEditor.scss
  assets/src/styles/blocks/Cookies/Cookies.scss
Labels: Review, UAT Passed, [Test Env] umbriel

#1170 PLANET-7286 Fix Media & Text parallax effect
  assets/src/components/Parallax/setupParallax.js
Labels: Review, [Test Env] rhea

#1173 PLANET-7314: Fix Page Header on small screens
  assets/src/styles/blocks/PageHeader.scss
Labels: Review, [Test Env] rhea

#1171 PLANET-7301: Ensure to not re-instantiate the Carousel Header block from plugin
  classes/blocks/class-carouselheader.php
Labels: Review, [Test Env] neptune

#1172 PLANET-7300: Ensure to not re-instantiate the Accrordion class block from plugin
  classes/blocks/class-accordion.php
Labels: Review, [Test Env] phobos

#1176 Make sure Spreadsheet block is not registered twice.
  classes/blocks/class-spreadsheet.php
Labels: Review, [Test Env] pandora

#1174 PLANET-7305: Make sure to not instantiate the Counter class twice
  classes/blocks/class-counter.php
Labels: Review, [Test Env] saturn

#1179 PLANET-7306: Make sure to not instantiate the Take Action Boxout class twice
  classes/blocks/class-takeactionboxout.php
Labels: Review
