Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-04, with the labels that each got.

#1027 PLANET-7112 Upgrade ESLint and Wordpress Plugin
  .eslintrc.json
  package-lock.json
  package.json
Labels: Review, [Test Env] janus

#1030 PLANET-7022 Apply new identity colors to Highlighted CTA pattern
  assets/src/block-templates/highlighted-cta/template.js
Labels: Review, UAT Passed, [Test Env] janus

#1032 Hotfix: ENForm fields select validation when no P4 EN Networks Form
  assets/src/blocks/ENForm/ENFormFrontend.js
Labels: Review, [Test Env] neptune

#1029 PLANET-7016 Apply the new colors to the Table block
  assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
  assets/src/blocks/toDeclarations.js
  assets/src/styles/blocks/Spreadsheet/SpreadsheetStyle.scss
  assets/src/styles/blocks/core-overrides/Table.scss
Labels: Review, [Test Env] saturn

#1034 PLANET-7130: Fix PageHeader content width
  assets/src/styles/blocks/PageHeader.scss
Labels: Review, [Test Env] oberon, [Test Env] neptune

#1031 PLANET-7014 Apply new identity colors to Accordion block
  assets/src/blocks/Accordion/AccordionEditorScript.js
  assets/src/styles/blocks/Accordion/AccordionStyle.scss
Labels: Review, UAT Passed, [Test Env] janus

#1036 Remove unnecesary ENForm.js
  assets/src/blocks/ENForm/ENForm.js
Labels: Review, [Test Env] leda

#1028 PLANET-7026 Apply new identity pattern background color
  assets/src/block-templates/deep-dive/block.json
  assets/src/block-templates/deep-dive/template.js
  assets/src/block-templates/issues/block.json
  assets/src/block-templates/issues/template.js
  assets/src/block-templates/page-header/block.json
  assets/src/block-templates/page-header/template.js
  assets/src/block-templates/quick-links/block.json
  assets/src/block-templates/quick-links/template.js
  assets/src/block-templates/reality-check/template.js
  assets/src/block-templates/side-image-with-text-and-cta/block.json
  assets/src/block-templates/side-image-with-text-and-cta/template.js
  classes/patterns/class-action.php
  classes/patterns/class-campaign.php
  classes/patterns/class-deepdivetopic.php
  classes/patterns/class-highleveltopic.php
  classes/patterns/class-homepage.php
  classes/patterns/class-takeaction.php
  classes/patterns/templates/class-gravityformwithimage.php
  classes/patterns/templates/class-gravityformwithtext.php
Labels: Review, UAT Passed, [Test Env] pandora
