Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-10, with the labels that each got.

#1135 Fix hydration-related console errors
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/Gallery/GalleryFrontend.js
Labels: Review, [Test Env] atlas

#1136 PLANET-7287 Social Media block crashes in the editor
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
Labels: Review, [Test Env] phoebe

#1118 Refactor Timeline block to use hydration
  assets/src/blocks/Timeline/TimelineBlock.js
  assets/src/blocks/Timeline/TimelineFrontend.js
  assets/src/blocks/Timeline/TimelineScript.js
  classes/blocks/class-timeline.php
Labels: Review, [Test Env] umbriel

#1119 Refactor ENForm block to use hydration
  assets/src/blocks/ENForm/ENFormBlock.js
  assets/src/blocks/ENForm/ENFormFrontend.js
  assets/src/blocks/ENForm/ENFormScript.js
  assets/src/blocks/ENForm/deprecated/ENFormV2.js
  assets/src/frontendIndex.js
  classes/blocks/class-enform.php
Labels: Review, [Test Env] leda

#1104 Refactor Covers block to use hydration
  assets/src/blocks/Covers/CoversBlock.js
  assets/src/blocks/Covers/CoversConstants.js
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/CoversFrontend.js
  assets/src/blocks/Covers/CoversScript.js
  assets/src/blocks/Covers/deprecated/coversV3.js
  classes/blocks/class-covers.php
Labels: Review, [Test Env] oberon

#1131 Refactor Split Two Columns block to use hydration
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsBlock.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsEditor.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsFrontend.js
  assets/src/blocks/SplitTwoColumns/SplitTwoColumnsScript.js
  classes/blocks/class-splittwocolumns.php
Labels: Review, [Test Env] pandora

#1139 Revert "Fix hydration-related console errors"
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/Gallery/GalleryFrontend.js
Labels: Review, [Test Env] saturn

#1137 PLANET-6917 Refactor Articles block to use hydration
  assets/src/blocks/Articles/ArticlesBlock.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/Articles/ArticlesScript.js
  classes/blocks/class-articles.php
Labels: Review

#1102 Refactor Spreadsheet block to use hydration
  assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
  assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
  assets/src/blocks/Spreadsheet/SpreadsheetScript.js
  assets/src/editorIndex.js
Labels: Review, [Test Env] iocaste

#1140 Add missing attribute to SlideBackground
  assets/src/blocks/CarouselHeader/CarouselHeaderFrontend.js
  assets/src/blocks/CarouselHeader/CarouselHeaderScript.js
  assets/src/blocks/CarouselHeader/SlideBackground.js
Labels: Review, [Test Env] phoebe

#1145 Fix some blocks fallback rendering
  assets/src/blocks/Covers/CoversScript.js
  assets/src/blocks/ENForm/ENFormScript.js
  assets/src/blocks/Timeline/TimelineScript.js
Labels: Review, [Test Env] umbriel

#1142 Refactor Spreadsheet sorting function to use dataset
  assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
Labels: Review, [Test Env] janus

#1146 Increase tests timeout times
  tests/e2e/env/.env.ci
Labels: [Test Env] titan

#1144 PLANET-7313: Fix header text cut off
  assets/src/styles/blocks/PageHeader.scss
Labels: Review, [Test Env] nix
