Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-02, with the labels that each got.

#1004 PLANET-7033: Allow list item in block list
  planet4-gutenberg-blocks.php
Labels: [Test Env] leda

#998 Remove unused JS e2e tests
  .eslintrc.json
  jest-puppeteer.config.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  tests/js/__snapshots__/articles.editor.spec.js.snap
  tests/js/__snapshots__/cookies.spec.js.snap
  tests/js/__snapshots__/counter.spec.js.snap
  tests/js/__snapshots__/spreadsheet.spec.js.snap
  tests/js/__snapshots__/submenu.spec.js.snap
  tests/js/articles.editor.spec.js
  tests/js/articles.frontend.spec.js
  tests/js/cookies.spec.js
  tests/js/counter.spec.js
  tests/js/e2e-tests-helpers.js
  tests/js/spreadsheet.spec.js
  tests/js/submenu.frontend.spec.js
  tests/js/submenu.spec.js
Labels: Review, [Test Env] pandora

#1012 Hotfix: Fix undefined values
  classes/class-loader.php
Labels: [Test Env] iocaste

#992 PLANET-7025 Fix Covers block 'Load more' button translation issue
  assets/src/blocks/Covers/CoversEditor.js
Labels: Review, [Test Env] saturn

#1015 PLANET-7094 Fix broken rounded images animation in Safari
  assets/src/variations/stretched-link/index.scss
Labels: Review

#1016 PLANET-7013 Make sure Deep Dive images are always round
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review, UAT Passed, [Test Env] rhea
