Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-01, with the labels that each got.

#988 Convert Issues pattern to a block template
  assets/src/block-templates/issues/block.json
  assets/src/block-templates/issues/index.js
  assets/src/block-templates/issues/template.js
  assets/src/block-templates/template-list.js
  assets/src/components/Image/ImageBlockEdit.js
  assets/src/styles/blocks/core-overrides/Image.scss
  classes/patterns/class-issues.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] rhea

#993 PLANET-6944 Convert Page Header Pattern into a Block Template
  assets/src/block-templates/page-header/block.json
  assets/src/block-templates/page-header/index.js
  assets/src/block-templates/page-header/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-pageheader.php
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] oberon

#987 PLANET-6941: Convert Highlighted CTA Pattern into a Block Template
  assets/src/block-templates/highlighted-cta/block.json
  assets/src/block-templates/highlighted-cta/index.js
  assets/src/block-templates/highlighted-cta/template.js
  assets/src/block-templates/template-list.js
  assets/src/blocks/Covers/TakeActionCovers.js
  classes/patterns/class-highleveltopic.php
  classes/patterns/class-highlightedcta.php
  planet4-gutenberg-blocks.php
Labels: [Test Env] iocaste, [Test Env] phobos
