Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2023-06, with the labels that each got.

#1058 PLANET-7067 Rewrite Columns Images test in Playwright
  tests/acceptance/ColumnsImagesCept.php
  tests/e2e/columns-images.spec.js
  tests/e2e/tools/lib/columns.js
Labels: Review, [Test Env] oberon

#1062 Stabilize some e2e tests
  tests/e2e/carousel-header.spec.js
  tests/e2e/editor-selector.spec.js
  tests/e2e/take-action-boxout.spec.js
  tests/e2e/tools/lib/columns.js
Labels: [Test Env] neptune

#1068 PLANET-7179 Fix Block report API error
  classes/search/class-patternsearch.php
Labels: Review, [Test Env] neptune

#1008 PLANET-7079: Convert Deep Dive Topic pattern layout into a Block Template
  assets/src/block-templates/deep-dive-topic/block.json
  assets/src/block-templates/deep-dive-topic/index.js
  assets/src/block-templates/deep-dive-topic/template.js
  assets/src/block-templates/page-header/block.json
  assets/src/block-templates/page-header/template.js
  assets/src/block-templates/reality-check/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-deepdivetopic.php
  planet4-gutenberg-blocks.php
Labels: [Test Env] atlas

#1063 PLANET-7165 Re-write Covers campaign test in Playwright
  tests/acceptance/CoversCampaignCept.php
  tests/e2e/covers-campaign.spec.js
  tests/e2e/tools/lib/covers.js
Labels: Review, [Test Env] telesto

#1066 PLANET-7083 Convert Homepage pattern layout to Block Templates
  assets/src/block-templates/homepage/block.json
  assets/src/block-templates/homepage/index.js
  assets/src/block-templates/homepage/template.js
  assets/src/block-templates/issues/block.json
  assets/src/block-templates/issues/template.js
  assets/src/block-templates/template-list.js
  assets/src/block-templates/templates/gravity-form-with-text.js
  classes/patterns/class-homepage.php
  planet4-gutenberg-blocks.php
Labels: Review

#1061 PLANET-7167 Re-write the Split Two Columns test in Playwright
  tests/acceptance/SplitTwoColumnsCept.php
  tests/e2e/split-two-columns.spec.js
Labels: Review

#1070 PLANET-7066 Rewrite Columns Icons test in Playwright
  tests/acceptance/ColumnsIconsCept.php
  tests/e2e/columns-icons.spec.js
  tests/e2e/tools/lib/columns.js
Labels: Review

#1067 PLANET-7082 Convert Campaign pattern layout into a Block Template
  assets/src/block-templates/campaign/block.json
  assets/src/block-templates/campaign/index.js
  assets/src/block-templates/campaign/template.js
  assets/src/block-templates/homepage/template.js
  assets/src/block-templates/page-header/block.json
  assets/src/block-templates/page-header/template.js
  assets/src/block-templates/template-list.js
  assets/src/block-templates/templates/gravity-form-with-text.js
  classes/patterns/class-campaign.php
  planet4-gutenberg-blocks.php
Labels: Review

#1064 PLANET-7166 Re-write Covers Take Action test in Playwright
  tests/acceptance/CoversTakeActionCept.php
  tests/e2e/covers-take-action.spec.js
  tests/e2e/tools/lib/covers.js
Labels: Review, [Test Env] deimos

#1065 PLANET-7164 Re-write Covers Content test in Playwright
  tests/acceptance/CoversContentCept.php
  tests/e2e/covers-content.spec.js
  tests/e2e/tools/lib/covers.js
Labels: Review, [Test Env] iocaste

#1073 PLANET-7170 Add help text to canonical link sidebar option
  assets/src/components/Sidebar/SearchEngineOptimizationsSidebar.js
Labels: Review, [Test Env] mars
