Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-02, with the labels that each got.

#1186 PLANET-7425 Fix ignore_categories behaviour for the Articles block
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/Articles/useArticlesFetch.js
  classes/blocks/class-articles.php
Labels: Review, [Test Env] rhea

#1181 fix: change gsutil into gcloud
  .circleci/config.yml
Labels: [Test Env] pluto

#1187 PLANET-7379 Remove sidebar fields from blocks plugin
  assets/src/components/NavigationType/NavigationType.js
  assets/src/components/Sidebar/ActionSidebar.js
  assets/src/components/Sidebar/AnalyticsTrackingSidebar.js
  assets/src/components/Sidebar/CampaignThemeSidebar.js
  assets/src/components/Sidebar/LocalThemeSettings.js
  assets/src/components/Sidebar/PageHeaderSidebar.js
  assets/src/components/Sidebar/PostParentLink.js
  assets/src/components/Sidebar/SearchEngineOptimizationsSidebar.js
  assets/src/components/Sidebar/ThemeSettings.js
  assets/src/components/Sidebar/getSidebarFunctions.js
  assets/src/components/SidebarFields/CheckboxSidebarField.js
  assets/src/components/SidebarFields/ImageSidebarField.js
  assets/src/components/SidebarFields/SelectSidebarField.js
  assets/src/components/SidebarFields/TextSidebarField.js
  assets/src/components/SidebarFields/TextareaSidebarField.js
  assets/src/components/fromThemeOptions/fromThemeOptions.js
  assets/src/editorIndex.js
  assets/src/saveMetaToPreview.js
  assets/src/setupCustomSidebar.js
  assets/src/theme/p4ServerThemes.js
Labels: Review, [Test Env] venus

#1188 Fix Page Header padding values
  assets/src/styles/blocks/PageHeader.scss
Labels: Review, UAT Passed, [Test Env] iocaste
