Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-04, with the labels that each got.

#1178 PLANET-7290 Make sure Timeline block is not registered twice
  classes/blocks/class-timeline.php
Labels: Review, [Test Env] jupiter

#1197 PLANET-7304 Move ENForm block to master theme
  classes/class-loader.php
  planet4-gutenberg-blocks.php
Labels: Review

#1199 Fix ENForm breaking page when missing title size
  assets/src/blocks/ENForm/ENFormFrontend.js
Labels: [Test Env] pandora

#1198 PLANET-7486 Fix Page Header block for RTL sites
  assets/src/styles/blocks/PageHeader.scss
Labels: Review, UAT Passed, [Test Env] oberon

#1200 Fix ENForm background color
  assets/src/styles/blocks/ENForm/ENFormEditorStyle.scss
  assets/src/styles/blocks/ENForm/components/_enform-full-width-bg.scss
  assets/src/styles/blocks/ENForm/components/_enform-full-width.scss
  assets/src/styles/blocks/ENForm/components/_enform.scss
Labels: Review, [Test Env] jupiter

#1190 PLANET-7344 Make featured image mandatory for publishing
  assets/src/BlockEditorValidation.js
  tests/e2e/articles.spec.js
  tests/e2e/carousel-header.spec.js
  tests/e2e/columns-icons.spec.js
  tests/e2e/columns-images.spec.js
  tests/e2e/columns-no-image.spec.js
  tests/e2e/columns-tasks.spec.js
  tests/e2e/covers-campaign.spec.js
  tests/e2e/covers-content.spec.js
  tests/e2e/covers-take-action.spec.js
  tests/e2e/editor-selector.spec.js
  tests/e2e/enform.spec.js
  tests/e2e/related-articles.spec.js
  tests/e2e/split-two-columns.spec.js
  tests/e2e/spreadsheet.spec.js
  tests/e2e/take-action-boxout.spec.js
  tests/e2e/tools/lib/columns.js
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/post.js
Labels: Review, [Test Env] rhea

#1201 PLANET-7442 Make sure P4 Columns block isn't registered twice
  classes/blocks/class-columns.php
Labels: Review, [Test Env] pandora

#1204 Rename object_to_array function
  planet4-gutenberg-blocks.php
  templates/blocks/enform/enform_post.twig
Labels: Review, [Test Env] iocaste
