Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-09, with the labels that each got.

#1234 Remove Take Action Boxout block
  assets/src/blocks/TakeActionBoxout/ImagePlaceholder.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
  assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
  assets/src/blocks/TakeActionBoxout/deprecated/takeActionBoxoutV1.js
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/TakeActionBoxout/edit.scss
  assets/src/styles/blocks/TakeActionBoxout/style.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-takeactionboxout.php
  classes/class-loader.php
  public/images/close-boxout.svg
  templates/blocks/take-action-boxout.twig
  tests/e2e/take-action-boxout.spec.js
Labels: Review, [Test Env] pluto

#1235 PLANET-7534 Allow Take Action Boxout in all post types
  planet4-gutenberg-blocks.php
Labels: Review, [Test Env] umbriel

#1237 PLANET-7220: Add definitions to blocks settings
  assets/src/blocks/Columns/ColumnsBlock.js
  assets/src/blocks/Columns/ColumnsEditor.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/SocialMedia/SocialMediaBlock.js
  assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
  assets/src/blocks/Submenu/SubmenuBlock.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/Timeline/TimelineBlock.js
  assets/src/blocks/Timeline/TimelineEditorScript.js
Labels: Review, UAT Passed

#1240 PLANET-7604 Remove block categories registration
  classes/class-loader.php
Labels: Review, [Test Env] nix

#1242 Remove Submenu block
  admin/images/submenu-sidebar.jpg
  assets/src/blocks/Submenu/SubmenuBlock.js
  assets/src/blocks/Submenu/SubmenuEditor.js
  assets/src/blocks/Submenu/SubmenuFrontend.js
  assets/src/blocks/Submenu/SubmenuItems.js
  assets/src/blocks/Submenu/SubmenuLevel.js
  assets/src/blocks/Submenu/example.js
  assets/src/blocks/Submenu/generateAnchor.js
  assets/src/blocks/Submenu/getHeadingsFromBlocks.js
  assets/src/blocks/Submenu/getHeadingsFromDom.js
  assets/src/blocks/Submenu/getSubmenuStyle.js
  assets/src/blocks/Submenu/makeHierarchical.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Submenu.scss
  assets/src/styles/blocks/SubmenuEditor.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-submenu.php
  classes/class-loader.php
  public/images/submenu-long.jpg
  public/images/submenu-short.jpg
  public/images/submenu-sidebar.jpg
  public/images/submenu.png
Labels: Review, [Test Env] nix

#1238 PLANET-7584 Remove our custom editor layout margin values
  assets/src/styles/editorStyle.scss
Labels: Review, UAT Passed, [Test Env] jupiter

#1244 PLANET-7560 Remove mandatory featured image check for patterns
  assets/src/BlockEditorValidation.js
Labels: Review, [Test Env] venus

#1243 PLANET-7615: Remove block post type filter
  planet4-gutenberg-blocks.php
Labels: Review

#1245 PLANET-7617 Remove core overrides style files
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/core-overrides/BlockSpacing.scss
  assets/src/styles/blocks/core-overrides/Heading.scss
  assets/src/styles/blocks/core-overrides/HeadingEditor.scss
  assets/src/styles/blocks/core-overrides/Image.scss
  assets/src/styles/blocks/core-overrides/Separator.scss
  assets/src/styles/blocks/core-overrides/Table.scss
  assets/src/styles/blocks/core-overrides/_columns.scss
  assets/src/styles/blocks/core-overrides/_media-text.scss
  assets/src/styles/editorStyle.scss
Labels: Review, [Test Env] venus

#1249 PLANET-7501 Show image credits in the editor even when no caption
  assets/src/components/Image/ImageBlockEdit.js
Labels: Review

#1246 PLANET-7611: Remove the Happy Point block
  assets/src/blocks/Happypoint/HappyPointConstants.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Happypoint/HappypointFrontend.js
  assets/src/blocks/Happypoint/OverrideFormHelp.js
  assets/src/blocks/Happypoint/deprecated/HappyPointV1.js
  assets/src/blocks/Happypoint/useHappypointImageData.js
  assets/src/blocks/Happypoint/useHubspotEmbedCode.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Happypoint.scss
  assets/src/styles/blocks/HappypointEditor.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-happypoint.php
  classes/class-loader.php
  classes/rest/class-rest-api.php
Labels: Review
