Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-10, with the labels that each got.

#1251 Revert "PLANET-7611: Remove the Happy Point block (#1246)"
  assets/src/blocks/Happypoint/HappyPointConstants.js
  assets/src/blocks/Happypoint/HappypointBlock.js
  assets/src/blocks/Happypoint/HappypointEditor.js
  assets/src/blocks/Happypoint/HappypointFrontend.js
  assets/src/blocks/Happypoint/OverrideFormHelp.js
  assets/src/blocks/Happypoint/deprecated/HappyPointV1.js
  assets/src/blocks/Happypoint/useHappypointImageData.js
  assets/src/blocks/Happypoint/useHubspotEmbedCode.js
  assets/src/editorIndex.js
  assets/src/frontendIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/blocks/Happypoint.scss
  assets/src/styles/blocks/HappypointEditor.scss
  assets/src/styles/editorStyle.scss
  classes/blocks/class-happypoint.php
  classes/class-loader.php
  classes/rest/class-rest-api.php
Labels: Review, [Test Env] pluto

#1252 Remove Stretched Link, Quick Links, and Deep Dive templates
  assets/src/block-templates/deep-dive/block.json
  assets/src/block-templates/deep-dive/index.js
  assets/src/block-templates/deep-dive/template.js
  assets/src/block-templates/quick-links/block.json
  assets/src/block-templates/quick-links/index.js
  assets/src/block-templates/quick-links/template.js
  assets/src/block-templates/template-list.js
  assets/src/editorIndex.js
  assets/src/styles/blocks.scss
  assets/src/styles/editorStyle.scss
  assets/src/variations/stretched-link/edit.scss
  assets/src/variations/stretched-link/index.scss
  classes/patterns/class-block-pattern.php
  classes/patterns/class-deepdive.php
  classes/patterns/class-quicklinks.php
  phpcs.xml
Labels: Review, UAT Passed, [Test Env] pluto

#1253 PLANET-7629 Remove Covers block from the plugin
  admin/js/editor.js
  assets/src/block-templates/action/block.json
  assets/src/block-templates/action/index.js
  assets/src/block-templates/action/template.js
  assets/src/block-templates/template-list.js
  assets/src/blocks/Covers/CampaignCovers.js
  assets/src/blocks/Covers/ContentCovers.js
  assets/src/blocks/Covers/Covers.js
  assets/src/blocks/Covers/CoversBlock.js
  assets/src/blocks/Covers/CoversCarouselLayout.js
  assets/src/blocks/Covers/CoversConstants.js
  assets/src/blocks/Covers/CoversEditor.js
  assets/src/blocks/Covers/CoversEditorScript.js
  assets/src/blocks/Covers/CoversFrontend.js
  assets/src/blocks/Covers/CoversGridLoadMoreButton.js
  assets/src/blocks/Covers/CoversImagePlaceholder.js
  assets/src/blocks/Covers/CoversScript.js
  assets/src/blocks/Covers/TakeActionCovers.js
  assets/src/blocks/Covers/deprecated/coversV1.js
  assets/src/blocks/Covers/deprecated/coversV2.js
  assets/src/blocks/Covers/deprecated/coversV3.js
  assets/src/blocks/Covers/example.js
  assets/src/blocks/Covers/imageSizes.js
  assets/src/blocks/Covers/useCovers.js
  assets/src/styles/blocks/Covers/CoversEditorStyle.scss
  assets/src/styles/blocks/Covers/CoversStyle.scss
  assets/src/styles/blocks/Covers/layouts/CoversCarouselLayout.scss
  assets/src/styles/blocks/Covers/layouts/CoversGridLayout.scss
  assets/src/styles/blocks/Covers/styles/CampaignCovers.scss
  assets/src/styles/blocks/Covers/styles/ContentCovers.scss
  assets/src/styles/blocks/Covers/styles/TakeActionCovers.scss
  classes/blocks/class-covers.php
  classes/class-loader.php
  classes/patterns/class-action.php
  classes/patterns/class-block-pattern.php
  classes/rest/class-rest-api.php
  public/images/climate/covers-block.svg
  public/images/oil/covers-block.svg
  tests/e2e/covers-campaign.spec.js
  tests/e2e/covers-content.spec.js
  tests/e2e/covers-take-action.spec.js
  tests/e2e/tools/lib/covers.js
  webpack.config.js
Labels: Review, [Test Env] tavros

#1257 PLANET-7628: Remove Articles block
  assets/src/blocks/Articles/ArticlePreview.js
  assets/src/blocks/Articles/ArticlesBlock.js
  assets/src/blocks/Articles/ArticlesEditor.js
  assets/src/blocks/Articles/ArticlesEditorScript.js
  assets/src/blocks/Articles/ArticlesFrontend.js
  assets/src/blocks/Articles/ArticlesList.js
  assets/src/blocks/Articles/ArticlesScript.js
  assets/src/blocks/Articles/imageSizes.js
  assets/src/blocks/Articles/useArticlesFetch.js
  assets/src/components/PostSelector/PostSelector.js
  assets/src/components/PostTypeSelector/PostTypeSelector.js
  assets/src/components/TagSelector/TagSelector.js
  assets/src/components/withCharacterCounter/withCharacterCounter.js
  assets/src/functions/useSelector.js
  assets/src/styles/blocks/Articles/ArticlesEditorStyle.scss
  assets/src/styles/blocks/Articles/ArticlesStyle.scss
  classes/blocks/class-articles.php
  classes/class-loader.php
  classes/rest/class-published.php
  classes/rest/class-rest-api.php
  tests/e2e/articles.spec.js
  tests/e2e/related-articles.spec.js
  tests/e2e/tools/lib/editor.js
  webpack.config.js
Labels: Review, [Test Env] pluto

#1259 PLANET-7446: Remove lightbox
  assets/src/blocks/Gallery/GalleryFrontend.js
  assets/src/components/Lightbox/Lightbox.js
  assets/src/components/Lightbox/setupLightboxForImages.js
  assets/src/components/Lightbox/useLightbox.js
  assets/src/frontendIndex.js
  assets/src/styles/lightbox.scss
  assets/src/styles/vendors/photoswipe/_main-settings.scss
  assets/src/styles/vendors/photoswipe/main.scss
  assets/src/styles/vendors/photoswipe/p4-skin.scss
  assets/src/styles/vendors/photoswipe/planet4-photoswipe.scss
  classes/class-loader.php
  public/images/vendors/photoswipe/default-skin.png
  public/images/vendors/photoswipe/default-skin.svg
  public/images/vendors/photoswipe/preloader.gif
  webpack.config.js
Labels: Review, [Test Env] tavros
