Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-05, with the labels that each got.

#1205 PLANET-7508: Modify Highlighted CTA block pattern template
  assets/src/block-templates/highlighted-cta/template.js
Labels: Review, UAT Passed, [Test Env] sinope

#1209 Fix panel editor spec
  tests/e2e/split-two-columns.spec.js
  tests/e2e/tools/lib/editor.js
Labels: [Test Env] umbriel

#1210 PLANET-7263 Media Archive: add in editor option for P4 blocks
  assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
  assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
  assets/src/blocks/CarouselHeader/EditableBackground.js
  classes/blocks/class-carouselheader.php
Labels: Review, [Test Env] oberon
