Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-07, with the labels that each got.

#1216 PLANET-7554 Remove Take Action block pattern layout from plugin
  assets/src/block-templates/take-action/block.json
  assets/src/block-templates/take-action/index.js
  assets/src/block-templates/take-action/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-block-pattern.php
  classes/patterns/class-takeaction.php
Labels: Review, [Test Env] nix

#1217 PLANET-7561 Remove Blank Page pattern
  classes/patterns/class-blankpage.php
  classes/patterns/class-block-pattern.php
  classes/search/pattern/class-patternusageapi.php
  classes/search/pattern/class-patternusagetable.php
Labels: [Test Env] umbriel

#1219 PLANET-7496: Backend Text Changes on Submenu Block
  assets/src/blocks/Submenu/SubmenuEditor.js
Labels: Review, UAT Passed, [Test Env] nix

#1215 PLANET-7527 Remove blocks report functionality from blocks plugin
  classes/class-loader.php
  classes/command/class-duplicated-postmeta.php
  classes/controller/menu/class-blocks-usage-controller.php
  classes/controller/menu/class-classic-blocks-usage.php
  classes/controller/menu/class-postmeta-check-controller.php
  classes/controller/menu/class-reusable-blocks-controller.php
  classes/controller/menu/class-settings-controller.php
  classes/search/block/class-blockusage.php
  classes/search/block/class-blockusageapi.php
  classes/search/block/class-blockusagetable.php
  classes/search/block/class-query.php
  classes/search/block/query/class-parameters.php
  classes/search/block/sql/class-like.php
  classes/search/block/sql/class-regex.php
  classes/search/block/sql/class-sqlquery.php
  classes/search/class-blocksearch.php
  classes/search/class-patternsearch.php
  classes/search/class-rowactions.php
  classes/search/pattern/class-contentstructure.php
  classes/search/pattern/class-patterndata.php
  classes/search/pattern/class-patternusage.php
  classes/search/pattern/class-patternusageapi.php
  classes/search/pattern/class-patternusagetable.php
  classes/search/pattern/query/class-parameters.php
  templates/duplicate-postmeta-report.twig
Labels: Review, [Test Env] venus

#1223 PLANET-7552 Remove High Level Topic block pattern layout
  assets/src/block-templates/high-level-topic/block.json
  assets/src/block-templates/high-level-topic/index.js
  assets/src/block-templates/high-level-topic/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-block-pattern.php
  classes/patterns/class-highleveltopic.php
Labels: [Test Env] titan

#1224 PLANET-7551: Remove GetInformed pattern block from plugin
  assets/src/block-templates/get-informed/block.json
  assets/src/block-templates/get-informed/index.js
  assets/src/block-templates/get-informed/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-block-pattern.php
  classes/patterns/class-getinformed.php
Labels: Review, [Test Env] titan
