Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-03, with the labels that each got.

#1191 Add code to prevent registering Social Media block twice
  classes/blocks/class-socialmedia.php
Labels: Review, [Test Env] sinope

#1189 PLANET-7426: Integrate reading time display value
  classes/blocks/class-articles.php
Labels: UAT Passed

#1193 Add check for Media block
  classes/blocks/class-media.php
Labels: Review, [Test Env] saturn

#1194 PLANET-7444 Fix left/right aligned images in all post types
  assets/src/styles/blocks/core-overrides/Image.scss
Labels: Review, [Test Env] pandora
