Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-01, with the labels that each got.

#1180 PLANET-7378: Make sure to not instantiate twice the Happypoint class
  classes/blocks/class-happypoint.php
Labels: Review, [Test Env] neptune

#1183 Update phpunit polyfills
  composer.json
  composer.lock
  tests/bootstrap.php
Labels: [Test Env] pandora

#1182 PLANET-6924: Fix Tag and Post Type selector
  assets/src/components/PostTypeSelector/PostTypeSelector.js
  assets/src/components/TagSelector/TagSelector.js
  assets/src/functions/useSelector.js
Labels: Review, [Test Env] saturn

#1184 PLANET-7382 Move Submenu block into master theme
  classes/blocks/class-submenu.php
Labels: Review
