Repository greenpeace/planet4-plugin-gutenberg-blocks, pull requests merged in 2024-08, with the labels that each got.

#1228 PLANET-7550: Remove Deep Dive Topic pattern block from plugin
  assets/src/block-templates/deep-dive-topic/block.json
  assets/src/block-templates/deep-dive-topic/index.js
  assets/src/block-templates/deep-dive-topic/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-block-pattern.php
  classes/patterns/class-deepdivetopic.php
Labels: Review, [Test Env] nix

#1226 PLANET-7565: Replaced deprecated imports in WordPress 6.6.x
  assets/src/BlockEditorValidation.js
Labels: Review

#1230 PLANET-7565: Fix tests broken by WordPress v6.6.x
  tests/e2e/tools/lib/editor.js
  tests/e2e/tools/lib/post.js
Labels: Review, [Test Env] mars

#1229 PLANET-7389 Add PHP8.3 tests job
  .circleci/config.yml
  composer.json
  composer.lock
Labels: Review

#1225 PLANET-7549: Remove Campaign pattern block from plugin
  assets/src/block-templates/campaign/block.json
  assets/src/block-templates/campaign/index.js
  assets/src/block-templates/campaign/template.js
  assets/src/block-templates/template-list.js
  classes/patterns/class-block-pattern.php
  classes/patterns/class-campaign.php
Labels: Review

#1227 PLANET-7548: Remove Action pattern block from plugin
  assets/src/block-templates/action/block.json
  assets/src/block-templates/action/index.js
  assets/src/block-templates/action/template.js
  assets/src/block-templates/template-list.js
  assets/src/block-templates/templates/gravity-form-with-text.js
  classes/patterns/class-action.php
  classes/patterns/class-block-pattern.php
Labels: Review, [Test Env] pluto

#1232 PLANET 7585: Explicity import `regenerator-runtime`
  assets/src/functions/fetchJson.js
Labels: Review, [Test Env] umbriel
